// Data Structure - Animals
const animals = {
    animal_ID: String,
    contact_ID: String,
    date_created: Date,
    date_updated: Date,
    name: String,
    enum_type: String,
    enum_category: String,
    enum_breed: String,
    enum_sex: String,
    enum_size: String,
    enum_flag: String,
    breed_optional: String,
    color: String,
    birth_year: Int,
    height: Int,
    weight: Int,
    length: Int,
    girth: Int,
    neck: Int,
    notes: String,
    active: Booleon,
    skills: {
        sit_stay: Boolean,
        down_stay: Boolean,
        stand_stay: Boolean,
        command_bark: Boolean,
        command_hold_object: Boolean,
        command_silent: Boolean,
        tolerance_handle: Boolean,
        tolerance_sound: Boolean,
        tolerance_dogs: Boolean,
        tolerance_small_animals: Boolean,
        tolerance_strangers: Boolean,
        tolerance_children: Boolean,
        work_at_distance: Boolean,
    },
};
