// Animal Breeds Module
export const animalBreeds = {
    dog: [
        {
            key: "sporting",
            label: "Sporting",
            breeds: [
                "American Water Spaniel",
                "Barbet",
                "Boykin Spaniel",
                "Bracco Italiano",
                "Brittany",
                "Chesapeake Bay Retriever",
                "Clumber Spaniel",
                "Cocker Spaniel",
                "Curly-Coated Retriever",
                "English Cocker Spaniel",
                "English Setter",
                "English Springer Spaniel",
                "Field Spaniel",
                "Flat-Coated Retriever",
                "German Shorthaired Pointer",
                "German Wirehaired Pointer",
                "Golden Retriever",
                "Gordon Setter",
                "Irish Red and White Setter",
                "Irish Setter",
                "Irish Water Spaniel",
                "Labrador Retriever",
                "Lagotto Romagnolo",
                "Nederlandse Kooikerhondje",
                "Nova Scotia Duck Tolling Retriever",
                "Pointer",
                "Spinone Italiano",
                "Sussex Spaniel",
                "Vizsla",
                "Weimaraner",
                "Welsh Springer Spaniel",
                "Wirehaired Pointing Griffon",
                "Wirehaired Vizsla",
                "Other",
            ],
        },
        {
            key: "hound",
            label: "Hound",
            breeds: [
                "Afghan Hound",
                "American English Coonhound",
                "American Foxhound",
                "Azawakh",
                "Basenji",
                "Basset Hound",
                "Beagle",
                "Black and Tan Coonhound",
                "Bloodhound",
                "Bluetick Coonhound",
                "Borzoi",
                "Cirneco dell’Etna",
                "Dachshund",
                "English Foxhound",
                "Grand Basset Griffon Vendeen",
                "Greyhound",
                "Harrier",
                "Ibizan Hound",
                "Irish Wolfhound",
                "Norwegian Elkhound",
                "Otterhound",
                "Petit Basset Griffon Vendeen",
                "Pharaoh Hound",
                "Plott Hound",
                "Portuguese Podengo Pequeno",
                "Redbone Coonhound",
                "Rhodesian Ridgeback",
                "Saluki",
                "Scottish Deerhound",
                "Sloughi",
                "Treeing Walker Coonhound",
                "Whippet",
                "Other",
            ],
        },
        {
            key: "working",
            label: "Working",
            breeds: [
                "Akita",
                "Alaskan Malamute",
                "Anatolian Shepherd Dog",
                "Bernese Mountain Dog",
                "Black Russian Terrier",
                "Boerboel",
                "Boxer",
                "Bullmastiff",
                "Cane Corso",
                "Chinook",
                "Danish-Swedish Farmdog",
                "Doberman Pinscher",
                "Dogo Argentino",
                "Dogue de Bordeaux",
                "German Pinscher",
                "Giant Schnauzer",
                "Great Dane",
                "Great Pyrenees",
                "Greater Swiss Mountain Dog",
                "Komondor",
                "Kuvasz",
                "Leonberger",
                "Mastiff",
                "Neapolitan Mastiff",
                "Newfoundland",
                "Portuguese Water Dog",
                "Rottweiler",
                "St. Bernard",
                "Samoyed",
                "Siberian Husky",
                "Standard Schnauzer",
                "Tibetan Mastiff",
                "Other",
            ],
        },
        {
            key: "terrier",
            label: "Terrier",
            breeds: [
                "Airedale Terrier",
                "American Hairless Terrier",
                "American Staffordshire Terrier",
                "Australian Terrier",
                "Bedlington Terrier",
                "Border Terrier",
                "Bull Terrier",
                "Cairn Terrier",
                "Cesky Terrier",
                "Dandie Dinmont Terrier",
                "Glen of Imaal Terrier",
                "Irish Terrier",
                "Kerry Blue Terrier",
                "Lakeland Terrier",
                "Manchester Terrier",
                "Miniature Bull Terrier",
                "Miniature Schnauzer",
                "Norfolk Terrier",
                "Norwich Terrier",
                "Parson Russell Terrier",
                "Rat Terrier",
                "Russell Terrier",
                "Scottish Terrier",
                "Sealyham Terrier",
                "Skye Terrier",
                "Smooth Fox Terrier",
                "Soft Coated Wheaton Terrier",
                "Staffordshire Bull Terrier",
                "Welsh Terrier",
                "West Highland White Terrier",
                "Wire Fox Terrier",
                "Other",
            ],
        },
        {
            key: "toy",
            label: "Toy",
            breeds: [
                "Affenpinscher",
                "Biewer Terrier",
                "Brussels Griffon",
                "Cavalier King Charles Spaniel",
                "Chihuahua",
                "Chinese Crested",
                "English Toy Spaniel",
                "Havanese",
                "Italian Greyhound",
                "Japanese Chin",
                "Maltese",
                "Manchester Terrier",
                "Miniature Pinscher",
                "Papillon",
                "Pekingese",
                "Pomeranian",
                "Poodle",
                "Pug",
                "Russian Toy",
                "Shih Tzu",
                "Silky Terrier",
                "Toy Fox Terrier",
                "Yorkshire Terrier",
                "Other",
            ],
        },
        {
            key: "non_sporting",
            label: "Non-Sporting",
            breeds: [
                "American Eskimo Dog",
                "Bichon Frise",
                "Boston Terrier",
                "Bulldog",
                "Chinese Shar-Pei",
                "Chow Chow",
                "Coton de Tulear",
                "Dalmatian",
                "Finnish Spitz",
                "French Bulldog",
                "Keeshond",
                "Lhasa Apso",
                "Lowchen",
                "Norwegian Lundehund",
                "Poodle",
                "Schipperke",
                "Shiba Inu",
                "Tibetan Spaniel",
                "Tibetan Terrier",
                "Xoloitzcuintli",
                "Other",
            ],
        },
        {
            key: "herding",
            label: "Herding",
            breeds: [
                "Australian Cattle Dog",
                "Australian Shepherd",
                "Bearded Collie",
                "Beauceron",
                "Belgian Laekenois",
                "Belgian Malinois",
                "Belgian Sheepdog",
                "Belgian Tervuren",
                "Bergamasco",
                "Berger Picard",
                "Border Collie",
                "Bouvier Des Flanders",
                "Briard",
                "Canaan Dog",
                "Cardigan Welsh Corgi",
                "Collie",
                "Entlebucher Mountain Dog",
                "Finnish Lapphund",
                "German Shepherd Dog",
                "Icelandic Sheepdog",
                "Lancashire Heeler",
                "Miniature American Shepherd",
                "Mudi",
                "Norwegian Buhund",
                "Old English Sheepdog",
                "Pembroke Welsh Corgi",
                "Polish Lowland Sheepdog",
                "Puli",
                "Pumi",
                "Pyrenean Shepherd",
                "Shetland Sheepdog",
                "Spanish Water Dog",
                "Swedish Vallhund",
                "Other",
            ],
        },
        {
            key: "mixed",
            label: "Mixed",
            breeds: ["Mixed"],
        },
        {
            key: "other",
            label: "Other",
            breeds: ["Other"],
        },
    ],

    cat: [
        {
            key: "short_hair",
            label: "Short Hair",
            breeds: [
                "American Shorthair",
                "British Shorthair",
                "Burmese",
                "Russian Blue",
                "Siamese",
                "Oriental Shorthair",
                "Abyssinian",
                "Egyptian Mau",
                "Manx",
                "Tonkinese",
                "Other",
            ],
        },
        {
            key: "medium_hair",
            label: "Medium Hair",
            breeds: [
                "Bengal",
                "Scottish Fold",
                "Norwegian Forest Cat",
                "Ragdoll",
                "Somali",
                "Turkish Van",
                "Japanese Bobtail",
                "Ocicat",
                "Balinese",
                "Havana Brown",
                "Other",
            ],
        },
        {
            key: "long_hair",
            label: "Long Hair",
            breeds: [
                "Persian",
                "Maine Coon",
                "Himalayan",
                "Birman",
                "Siberian",
                "Ragamuffin",
                "Turkish Angora",
                "Chantilly-Tiffany",
                "Somali Longhair",
                "Scottish Longhair",
                "Other",
            ],
        },
        {
            key: "hairless",
            label: "Hairless",
            breeds: [
                "Sphynx",
                "Peterbald",
                "Donskoy",
                "Bambino",
                "Ukrainian Levkoy",
                "Other",
            ],
        },
        {
            key: "other",
            label: "Other",
            breeds: ["Other"],
        },
    ],

    horse: [
        {
            key: "riding",
            label: "Riding",
            breeds: [
                "American Quarter Horse",
                "Thoroughbred",
                "Arabian",
                "Appaloosa",
                "Morgan",
                "Hanoverian",
                "Trakehner",
                "Andalusian",
                "Lusitano",
                "Warmblood",
                "Other",
            ],
        },
        {
            key: "working",
            label: "Working",
            breeds: [
                "Clydesdale",
                "Percheron",
                "Belgian",
                "Shire",
                "American Cream Draft",
                "Suffolk Punch",
                "Freiberger",
                "Hackney",
                "American Standardbred",
                "Irish Draught",
                "Other",
            ],
        },
        {
            key: "pony",
            label: "Pony",
            breeds: [
                "Shetland Pony",
                "Welsh Pony",
                "Connemara Pony",
                "Fjord Pony",
                "Dartmoor Pony",
                "Haflinger",
                "New Forest Pony",
                "Exmoor Pony",
                "Chincoteague Pony",
                "Pony of the Americas",
                "Other",
            ],
        },
        {
            key: "miniature",
            label: "Miniature",
            breeds: [
                "Miniature Horse",
                "American Miniature Horse",
                "Falabella",
                "Miniature Shetland",
                "Miniature Appaloosa",
                "Other",
            ],
        },
        {
            key: "mixed",
            label: "Mixed",
            breeds: ["Mixed"],
        },
        {
            key: "other",
            label: "Other",
            breeds: ["Other"],
        },
    ],

    livestock: [
        {
            key: "cattle",
            label: "Cattle",
            breeds: [
                "Holstein",
                "Angus",
                "Hereford",
                "Jersey",
                "Simmental",
                "Other",
            ],
        },
        {
            key: "sheep",
            label: "Sheep",
            breeds: [
                "Merino",
                "Suffolk",
                "Dorset",
                "Hampshire",
                "Romney",
                "Other",
            ],
        },
        {
            key: "pig",
            label: "Pig",
            breeds: [
                "Yorkshire",
                "Berkshire",
                "Duroc",
                "Hampshire",
                "Landrace",
                "Other",
            ],
        },
        {
            key: "goat",
            label: "Goat",
            breeds: [
                "Nubian",
                "Boer",
                "Saanen",
                "Alpine",
                "Toggenburg",
                "Other",
            ],
        },
        {
            key: "llama_alpaca",
            label: "Llama/Alpaca",
            breeds: [
                "Classic Llama",
                "Suri Llama",
                "Huacaya Llama",
                "Huacaya Alpaca",
                "Suri Alpaca",
                "Other",
            ],
        },
        {
            key: "poultry",
            label: "Poultry",
            breeds: [
                "Rhode Island Red",
                "Leghorn",
                "Plymouth Rock",
                "Sussex",
                "Orpington",
                "Other",
            ],
        },
        {
            key: "other",
            label: "Other",
            breeds: ["Other"],
        },
    ],

    small_pet: [
        {
            key: "bird",
            label: "Bird",
            breeds: [
                "Budgie",
                "Cockatiel",
                "Lovebird",
                "Parakeet",
                "Canary",
                "Finch",
                "African Grey Parrot",
                "Cockatoo",
                "Macaw",
                "Other",
            ],
        },
        {
            key: "hamster",
            label: "Hamster",
            breeds: [
                "Syrian Hamster",
                "Roborovski Hamster",
                "Chinese Hamster",
                "Other",
            ],
        },
        {
            key: "bunny",
            label: "Bunny",
            breeds: [
                "Holland Lop",
                "Netherland Dwarf",
                "Lionhead",
                "Mini Rex",
                "Flemish Giant",
                "Other",
            ],
        },
        {
            key: "guinea_pig",
            label: "Guinea Pig",
            breeds: [
                "American",
                "Abyssinian",
                "Peruvian",
                "Sheltie",
                "Teddy",
                "Other",
            ],
        },
        {
            key: "mouse",
            label: "Mouse",
            breeds: ["Fancy Mouse", "Burmese Mouse", "Satin Mouse", "Other"],
        },
        {
            key: "rat",
            label: "Rat",
            breeds: ["Standard Rat", "Dumbo Rat", "Hairless Rat", "Other"],
        },
        {
            key: "ferret",
            label: "Ferret",
            breeds: [
                "Standard Ferret",
                "Albino Ferret",
                "Sable Ferret",
                "Silver Ferret",
                "Other",
            ],
        },
        {
            key: "other",
            label: "Other",
            breeds: ["Other"],
        },
    ],

    other: [
        {
            key: "wildlife",
            label: "Wildlife",
            breeds: ["Wildlife"],
        },
        {
            key: "exotic",
            label: "Exotic",
            breeds: ["Exotic"],
        },
        {
            key: "other",
            label: "Other",
            breeds: ["Other"],
        },
    ],
};
