// Fetch Category by Type if Type is Provided
// Otherwise, Fetch All Categories
export function getAnimalBreeds(type, category) {
    if (type && category) {
        return animalBreeds.filter((breed) => breed.type === type && breed.category === category);
    } else {
        return animalBreeds;
    }
}

// Fetch Specific Breed
export function getAnimalBreed(key, type, category) {
    return animalBreeds.find((breed) => breed.key === key && breed.type === type && breed.category === category);
}

// Define Breeds
const animalBreeds = [
    {
        key: "american_water_spaniel",
        type: "dog",
        category: "sporting",
        label: "American Water Spaniel",
        plural: "American Water Spaniels",
    },
    { key: "barbet", type: "dog", category: "sporting", label: "Barbet", plural: "Barbets" },
    { key: "boykin_spaniel", type: "dog", category: "sporting", label: "Boykin Spaniel", plural: "Boykin Spaniels" },
    { key: "bracco_italiano", type: "dog", category: "sporting", label: "Bracco Italiano", plural: "Bracco Italianos" },
    { key: "brittany", type: "dog", category: "sporting", label: "Brittany", plural: "Brittanies" },
    {
        key: "chesapeake_bay_retriever",
        type: "dog",
        category: "sporting",
        label: "Chesapeake Bay Retriever",
        plural: "Chesapeake Bay Retrievers",
    },
    { key: "clumber_spaniel", type: "dog", category: "sporting", label: "Clumber Spaniel", plural: "Clumber Spaniels" },
    { key: "cocker_spaniel", type: "dog", category: "sporting", label: "Cocker Spaniel", plural: "Cocker Spaniels" },
    {
        key: "curly_coated_retriever",
        type: "dog",
        category: "sporting",
        label: "Curly-Coated Retriever",
        plural: "Curly-Coated Retrievers",
    },
    {
        key: "english_cocker_spaniel",
        type: "dog",
        category: "sporting",
        label: "English Cocker Spaniel",
        plural: "English Cocker Spaniels",
    },
    { key: "english_setter", type: "dog", category: "sporting", label: "English Setter", plural: "English Setters" },
    {
        key: "english_springer_spaniel",
        type: "dog",
        category: "sporting",
        label: "English Springer Spaniel",
        plural: "English Springer Spaniels",
    },
    { key: "field_spaniel", type: "dog", category: "sporting", label: "Field Spaniel", plural: "Field Spaniels" },
    {
        key: "flat_coated_retriever",
        type: "dog",
        category: "sporting",
        label: "Flat-Coated Retriever",
        plural: "Flat-Coated Retrievers",
    },
    {
        key: "german_shorthaired_pointer",
        type: "dog",
        category: "sporting",
        label: "German Shorthaired Pointer",
        plural: "German Shorthaired Pointers",
    },
    {
        key: "german_wirehaired_pointer",
        type: "dog",
        category: "sporting",
        label: "German Wirehaired Pointer",
        plural: "German Wirehaired Pointers",
    },
    {
        key: "golden_retriever",
        type: "dog",
        category: "sporting",
        label: "Golden Retriever",
        plural: "Golden Retrievers",
    },
    { key: "gordon_setter", type: "dog", category: "sporting", label: "Gordon Setter", plural: "Gordon Setters" },
    {
        key: "irish_red_and_white_setter",
        type: "dog",
        category: "sporting",
        label: "Irish Red and White Setter",
        plural: "Irish Red and White Setters",
    },
    { key: "irish_setter", type: "dog", category: "sporting", label: "Irish Setter", plural: "Irish Setters" },
    {
        key: "irish_water_spaniel",
        type: "dog",
        category: "sporting",
        label: "Irish Water Spaniel",
        plural: "Irish Water Spaniels",
    },
    {
        key: "labrador_retriever",
        type: "dog",
        category: "sporting",
        label: "Labrador Retriever",
        plural: "Labrador Retrievers",
    },
    {
        key: "lagotto_romagnolo",
        type: "dog",
        category: "sporting",
        label: "Lagotto Romagnolo",
        plural: "Lagotto Romagnolos",
    },
    {
        key: "nederlandse_kooikerhondje",
        type: "dog",
        category: "sporting",
        label: "Nederlandse Kooikerhondje",
        plural: "Nederlandse Kooikerhondjes",
    },
    {
        key: "nova_scotia_duck_tolling_retriever",
        type: "dog",
        category: "sporting",
        label: "Nova Scotia Duck Tolling Retriever",
        plural: "Nova Scotia Duck Tolling Retrievers",
    },
    { key: "pointer", type: "dog", category: "sporting", label: "Pointer", plural: "Pointers" },
    {
        key: "spinone_italiano",
        type: "dog",
        category: "sporting",
        label: "Spinone Italiano",
        plural: "Spinone Italianos",
    },
    { key: "sussex_spaniel", type: "dog", category: "sporting", label: "Sussex Spaniel", plural: "Sussex Spaniels" },
    { key: "vizsla", type: "dog", category: "sporting", label: "Vizsla", plural: "Vizslas" },
    { key: "weimaraner", type: "dog", category: "sporting", label: "Weimaraner", plural: "Weimaraners" },
    {
        key: "welsh_springer_spaniel",
        type: "dog",
        category: "sporting",
        label: "Welsh Springer Spaniel",
        plural: "Welsh Springer Spaniels",
    },
    {
        key: "wirehaired_pointing_griffon",
        type: "dog",
        category: "sporting",
        label: "Wirehaired Pointing Griffon",
        plural: "Wirehaired Pointing Griffons",
    },
    {
        key: "wirehaired_vizsla",
        type: "dog",
        category: "sporting",
        label: "Wirehaired Vizsla",
        plural: "Wirehaired Vizslas",
    },
    { key: "afghan_hound", type: "dog", category: "hound", label: "Afghan Hound", plural: "Afghan Hounds" },
    {
        key: "american_english_coonhound",
        type: "dog",
        category: "hound",
        label: "American English Coonhound",
        plural: "American English Coonhounds",
    },
    {
        key: "american_foxhound",
        type: "dog",
        category: "hound",
        label: "American Foxhound",
        plural: "American Foxhounds",
    },
    { key: "azawakh", type: "dog", category: "hound", label: "Azawakh", plural: "Azawakhs" },
    { key: "basenji", type: "dog", category: "hound", label: "Basenji", plural: "Basenjis" },
    { key: "basset_hound", type: "dog", category: "hound", label: "Basset Hound", plural: "Basset Hounds" },
    { key: "beagle", type: "dog", category: "hound", label: "Beagle", plural: "Beagles" },
    {
        key: "black_and_tan_coonhound",
        type: "dog",
        category: "hound",
        label: "Black and Tan Coonhound",
        plural: "Black and Tan Coonhounds",
    },
    { key: "bloodhound", type: "dog", category: "hound", label: "Bloodhound", plural: "Bloodhounds" },
    {
        key: "bluetick_coonhound",
        type: "dog",
        category: "hound",
        label: "Bluetick Coonhound",
        plural: "Bluetick Coonhounds",
    },
    { key: "borzoi", type: "dog", category: "hound", label: "Borzoi", plural: "Borzoi" },
    {
        key: "cirneco_dell_etna",
        type: "dog",
        category: "hound",
        label: "Cirneco dell’Etna",
        plural: "Cirneco dell’Etnas",
    },
    { key: "dachshund", type: "dog", category: "hound", label: "Dachshund", plural: "Dachshunds" },
    { key: "english_foxhound", type: "dog", category: "hound", label: "English Foxhound", plural: "English Foxhounds" },
    {
        key: "grand_basset_griffon_vendeen",
        type: "dog",
        category: "hound",
        label: "Grand Basset Griffon Vendeen",
        plural: "Grand Basset Griffon Vendeens",
    },
    { key: "greyhound", type: "dog", category: "hound", label: "Greyhound", plural: "Greyhounds" },
    { key: "harrier", type: "dog", category: "hound", label: "Harrier", plural: "Harriers" },
    { key: "ibizan_hound", type: "dog", category: "hound", label: "Ibizan Hound", plural: "Ibizan Hounds" },
    { key: "irish_wolfhound", type: "dog", category: "hound", label: "Irish Wolfhound", plural: "Irish Wolfhounds" },
    {
        key: "norwegian_elkhound",
        type: "dog",
        category: "hound",
        label: "Norwegian Elkhound",
        plural: "Norwegian Elkhounds",
    },
    { key: "otterhound", type: "dog", category: "hound", label: "Otterhound", plural: "Otterhounds" },
    {
        key: "petit_basset_griffon_vendeen",
        type: "dog",
        category: "hound",
        label: "Petit Basset Griffon Vendeen",
        plural: "Petit Basset Griffon Vendeens",
    },
    { key: "pharaoh_hound", type: "dog", category: "hound", label: "Pharaoh Hound", plural: "Pharaoh Hounds" },
    { key: "plott_hound", type: "dog", category: "hound", label: "Plott Hound", plural: "Plott Hounds" },
    {
        key: "portuguese_podengo_pequeno",
        type: "dog",
        category: "hound",
        label: "Portuguese Podengo Pequeno",
        plural: "Portuguese Podengo Pequenos",
    },
    {
        key: "redbone_coonhound",
        type: "dog",
        category: "hound",
        label: "Redbone Coonhound",
        plural: "Redbone Coonhounds",
    },
    {
        key: "rhodesian_ridgeback",
        type: "dog",
        category: "hound",
        label: "Rhodesian Ridgeback",
        plural: "Rhodesian Ridgebacks",
    },
    { key: "saluki", type: "dog", category: "hound", label: "Saluki", plural: "Salukis" },
    {
        key: "scottish_deerhound",
        type: "dog",
        category: "hound",
        label: "Scottish Deerhound",
        plural: "Scottish Deerhounds",
    },
    { key: "sloughi", type: "dog", category: "hound", label: "Sloughi", plural: "Sloughis" },
    {
        key: "treeing_walker_coonhound",
        type: "dog",
        category: "hound",
        label: "Treeing Walker Coonhound",
        plural: "Treeing Walker Coonhounds",
    },
    { key: "whippet", type: "dog", category: "hound", label: "Whippet", plural: "Whippets" },

    { key: "akita", type: "dog", category: "working", label: "Akita", plural: "Akitas" },
    {
        key: "alaskan_malamute",
        type: "dog",
        category: "working",
        label: "Alaskan Malamute",
        plural: "Alaskan Malamutes",
    },
    {
        key: "anatolian_shepherd_dog",
        type: "dog",
        category: "working",
        label: "Anatolian Shepherd Dog",
        plural: "Anatolian Shepherd Dogs",
    },
    {
        key: "bernese_mountain_dog",
        type: "dog",
        category: "working",
        label: "Bernese Mountain Dog",
        plural: "Bernese Mountain Dogs",
    },
    {
        key: "black_russian_terrier",
        type: "dog",
        category: "working",
        label: "Black Russian Terrier",
        plural: "Black Russian Terriers",
    },
    { key: "boerboel", type: "dog", category: "working", label: "Boerboel", plural: "Boerboels" },
    { key: "boxer", type: "dog", category: "working", label: "Boxer", plural: "Boxers" },
    { key: "bullmastiff", type: "dog", category: "working", label: "Bullmastiff", plural: "Bullmastiffs" },
    { key: "cane_corso", type: "dog", category: "working", label: "Cane Corso", plural: "Cane Corsos" },
    { key: "chinook", type: "dog", category: "working", label: "Chinook", plural: "Chinooks" },
    {
        key: "danish_swedish_farmdog",
        type: "dog",
        category: "working",
        label: "Danish-Swedish Farmdog",
        plural: "Danish-Swedish Farmdogs",
    },
    {
        key: "doberman_pinscher",
        type: "dog",
        category: "working",
        label: "Doberman Pinscher",
        plural: "Doberman Pinschers",
    },
    { key: "dogo_argentino", type: "dog", category: "working", label: "Dogo Argentino", plural: "Dogo Argentinos" },
    {
        key: "dogue_de_bordeaux",
        type: "dog",
        category: "working",
        label: "Dogue de Bordeaux",
        plural: "Dogues de Bordeaux",
    },
    { key: "german_pinscher", type: "dog", category: "working", label: "German Pinscher", plural: "German Pinschers" },
    { key: "giant_schnauzer", type: "dog", category: "working", label: "Giant Schnauzer", plural: "Giant Schnauzers" },
    { key: "great_dane", type: "dog", category: "working", label: "Great Dane", plural: "Great Danes" },
    { key: "great_pyrenees", type: "dog", category: "working", label: "Great Pyrenees", plural: "Great Pyrenees" },
    {
        key: "greater_swiss_mountain_dog",
        type: "dog",
        category: "working",
        label: "Greater Swiss Mountain Dog",
        plural: "Greater Swiss Mountain Dogs",
    },
    { key: "komondor", type: "dog", category: "working", label: "Komondor", plural: "Komondors" },
    { key: "kuvasz", type: "dog", category: "working", label: "Kuvasz", plural: "Kuvasz" },
    { key: "leonberger", type: "dog", category: "working", label: "Leonberger", plural: "Leonbergers" },
    { key: "mastiff", type: "dog", category: "working", label: "Mastiff", plural: "Mastiffs" },
    {
        key: "neapolitan_mastiff",
        type: "dog",
        category: "working",
        label: "Neapolitan Mastiff",
        plural: "Neapolitan Mastiffs",
    },
    { key: "newfoundland", type: "dog", category: "working", label: "Newfoundland", plural: "Newfoundlands" },
    {
        key: "portuguese_water_dog",
        type: "dog",
        category: "working",
        label: "Portuguese Water Dog",
        plural: "Portuguese Water Dogs",
    },
    { key: "rottweiler", type: "dog", category: "working", label: "Rottweiler", plural: "Rottweilers" },
    { key: "st_bernard", type: "dog", category: "working", label: "St. Bernard", plural: "St. Bernards" },
    { key: "samoyed", type: "dog", category: "working", label: "Samoyed", plural: "Samoyeds" },
    { key: "siberian_husky", type: "dog", category: "working", label: "Siberian Husky", plural: "Siberian Huskies" },
    {
        key: "standard_schnauzer",
        type: "dog",
        category: "working",
        label: "Standard Schnauzer",
        plural: "Standard Schnauzers",
    },
    { key: "tibetan_mastiff", type: "dog", category: "working", label: "Tibetan Mastiff", plural: "Tibetan Mastiffs" },

    {
        key: "airedale_terrier",
        type: "dog",
        category: "terrier",
        label: "Airedale Terrier",
        plural: "Airedale Terriers",
    },
    {
        key: "american_hairless_terrier",
        type: "dog",
        category: "terrier",
        label: "American Hairless Terrier",
        plural: "American Hairless Terriers",
    },
    {
        key: "american_staffordshire_terrier",
        type: "dog",
        category: "terrier",
        label: "American Staffordshire Terrier",
        plural: "American Staffordshire Terriers",
    },
    {
        key: "australian_terrier",
        type: "dog",
        category: "terrier",
        label: "Australian Terrier",
        plural: "Australian Terriers",
    },
    {
        key: "bedlington_terrier",
        type: "dog",
        category: "terrier",
        label: "Bedlington Terrier",
        plural: "Bedlington Terriers",
    },
    { key: "border_terrier", type: "dog", category: "terrier", label: "Border Terrier", plural: "Border Terriers" },
    { key: "bull_terrier", type: "dog", category: "terrier", label: "Bull Terrier", plural: "Bull Terriers" },
    { key: "cairn_terrier", type: "dog", category: "terrier", label: "Cairn Terrier", plural: "Cairn Terriers" },
    { key: "cesky_terrier", type: "dog", category: "terrier", label: "Cesky Terrier", plural: "Cesky Terriers" },
    {
        key: "dandie_dinmont_terrier",
        type: "dog",
        category: "terrier",
        label: "Dandie Dinmont Terrier",
        plural: "Dandie Dinmont Terriers",
    },
    {
        key: "glen_of_imaal_terrier",
        type: "dog",
        category: "terrier",
        label: "Glen of Imaal Terrier",
        plural: "Glen of Imaal Terriers",
    },
    { key: "irish_terrier", type: "dog", category: "terrier", label: "Irish Terrier", plural: "Irish Terriers" },
    {
        key: "kerry_blue_terrier",
        type: "dog",
        category: "terrier",
        label: "Kerry Blue Terrier",
        plural: "Kerry Blue Terriers",
    },
    {
        key: "lakeland_terrier",
        type: "dog",
        category: "terrier",
        label: "Lakeland Terrier",
        plural: "Lakeland Terriers",
    },
    {
        key: "manchester_terrier",
        type: "dog",
        category: "terrier",
        label: "Manchester Terrier",
        plural: "Manchester Terriers",
    },
    {
        key: "miniature_bull_terrier",
        type: "dog",
        category: "terrier",
        label: "Miniature Bull Terrier",
        plural: "Miniature Bull Terriers",
    },
    {
        key: "miniature_schnauzer",
        type: "dog",
        category: "terrier",
        label: "Miniature Schnauzer",
        plural: "Miniature Schnauzers",
    },
    { key: "norfolk_terrier", type: "dog", category: "terrier", label: "Norfolk Terrier", plural: "Norfolk Terriers" },
    { key: "norwich_terrier", type: "dog", category: "terrier", label: "Norwich Terrier", plural: "Norwich Terriers" },
    {
        key: "parson_russell_terrier",
        type: "dog",
        category: "terrier",
        label: "Parson Russell Terrier",
        plural: "Parson Russell Terriers",
    },
    { key: "rat_terrier", type: "dog", category: "terrier", label: "Rat Terrier", plural: "Rat Terriers" },
    { key: "russell_terrier", type: "dog", category: "terrier", label: "Russell Terrier", plural: "Russell Terriers" },
    {
        key: "scottish_terrier",
        type: "dog",
        category: "terrier",
        label: "Scottish Terrier",
        plural: "Scottish Terriers",
    },
    {
        key: "sealyham_terrier",
        type: "dog",
        category: "terrier",
        label: "Sealyham Terrier",
        plural: "Sealyham Terriers",
    },
    { key: "skye_terrier", type: "dog", category: "terrier", label: "Skye Terrier", plural: "Skye Terriers" },
    {
        key: "smooth_fox_terrier",
        type: "dog",
        category: "terrier",
        label: "Smooth Fox Terrier",
        plural: "Smooth Fox Terriers",
    },
    {
        key: "soft_coated_wheaton_terrier",
        type: "dog",
        category: "terrier",
        label: "Soft Coated Wheaton Terrier",
        plural: "Soft Coated Wheaton Terriers",
    },
    {
        key: "staffordshire_bull_terrier",
        type: "dog",
        category: "terrier",
        label: "Staffordshire Bull Terrier",
        plural: "Staffordshire Bull Terriers",
    },
    { key: "welsh_terrier", type: "dog", category: "terrier", label: "Welsh Terrier", plural: "Welsh Terriers" },
    {
        key: "west_highland_white_terrier",
        type: "dog",
        category: "terrier",
        label: "West Highland White Terrier",
        plural: "West Highland White Terriers",
    },
    {
        key: "wire_fox_terrier",
        type: "dog",
        category: "terrier",
        label: "Wire Fox Terrier",
        plural: "Wire Fox Terriers",
    },

    { key: "affenpinscher", type: "dog", category: "toy", label: "Affenpinscher", plural: "Affenpinschers" },
    { key: "biewer_terrier", type: "dog", category: "toy", label: "Biewer Terrier", plural: "Biewer Terriers" },
    { key: "brussels_griffon", type: "dog", category: "toy", label: "Brussels Griffon", plural: "Brussels Griffons" },
    {
        key: "cavalier_king_charles_spaniel",
        type: "dog",
        category: "toy",
        label: "Cavalier King Charles Spaniel",
        plural: "Cavalier King Charles Spaniels",
    },
    { key: "chihuahua", type: "dog", category: "toy", label: "Chihuahua", plural: "Chihuahuas" },
    { key: "chinese_crested", type: "dog", category: "toy", label: "Chinese Crested", plural: "Chinese Cresteds" },
    {
        key: "english_toy_spaniel",
        type: "dog",
        category: "toy",
        label: "English Toy Spaniel",
        plural: "English Toy Spaniels",
    },
    { key: "havanese", type: "dog", category: "toy", label: "Havanese", plural: "Havanese" },
    {
        key: "italian_greyhound",
        type: "dog",
        category: "toy",
        label: "Italian Greyhound",
        plural: "Italian Greyhounds",
    },
    { key: "japanese_chin", type: "dog", category: "toy", label: "Japanese Chin", plural: "Japanese Chins" },
    { key: "maltese", type: "dog", category: "toy", label: "Maltese", plural: "Malteses" },
    {
        key: "manchester_terrier",
        type: "dog",
        category: "toy",
        label: "Manchester Terrier",
        plural: "Manchester Terriers",
    },
    {
        key: "miniature_pinscher",
        type: "dog",
        category: "toy",
        label: "Miniature Pinscher",
        plural: "Miniature Pinschers",
    },
    { key: "papillon", type: "dog", category: "toy", label: "Papillon", plural: "Papillons" },
    { key: "pekingese", type: "dog", category: "toy", label: "Pekingese", plural: "Pekingese" },
    { key: "pomeranian", type: "dog", category: "toy", label: "Pomeranian", plural: "Pomeranians" },
    { key: "poodle", type: "dog", category: "toy", label: "Poodle", plural: "Poodles" },
    { key: "pug", type: "dog", category: "toy", label: "Pug", plural: "Pugs" },
    { key: "russian_toy", type: "dog", category: "toy", label: "Russian Toy", plural: "Russian Toys" },
    { key: "shih_tzu", type: "dog", category: "toy", label: "Shih Tzu", plural: "Shih Tzus" },
    { key: "silky_terrier", type: "dog", category: "toy", label: "Silky Terrier", plural: "Silky Terriers" },
    { key: "toy_fox_terrier", type: "dog", category: "toy", label: "Toy Fox Terrier", plural: "Toy Fox Terriers" },
    {
        key: "yorkshire_terrier",
        type: "dog",
        category: "toy",
        label: "Yorkshire Terrier",
        plural: "Yorkshire Terriers",
    },

    {
        key: "american_eskimo_dog",
        type: "dog",
        category: "non_sporting",
        label: "American Eskimo Dog",
        plural: "American Eskimo Dogs",
    },
    { key: "bichon_frise", type: "dog", category: "non_sporting", label: "Bichon Frise", plural: "Bichon Frises" },
    {
        key: "boston_terrier",
        type: "dog",
        category: "non_sporting",
        label: "Boston Terrier",
        plural: "Boston Terriers",
    },
    { key: "bulldog", type: "dog", category: "non_sporting", label: "Bulldog", plural: "Bulldogs" },
    {
        key: "chinese_shar_pei",
        type: "dog",
        category: "non_sporting",
        label: "Chinese Shar-Pei",
        plural: "Chinese Shar-Peis",
    },
    { key: "chow_chow", type: "dog", category: "non_sporting", label: "Chow Chow", plural: "Chow Chows" },
    {
        key: "coton_de_tulear",
        type: "dog",
        category: "non_sporting",
        label: "Coton de Tulear",
        plural: "Coton de Tulears",
    },
    { key: "dalmatian", type: "dog", category: "non_sporting", label: "Dalmatian", plural: "Dalmatians" },
    { key: "finnish_spitz", type: "dog", category: "non_sporting", label: "Finnish Spitz", plural: "Finnish Spitzes" },
    {
        key: "french_bulldog",
        type: "dog",
        category: "non_sporting",
        label: "French Bulldog",
        plural: "French Bulldogs",
    },
    { key: "keeshond", type: "dog", category: "non_sporting", label: "Keeshond", plural: "Keeshonds" },
    { key: "lhasa_apso", type: "dog", category: "non_sporting", label: "Lhasa Apso", plural: "Lhasa Apsos" },
    { key: "lowchen", type: "dog", category: "non_sporting", label: "Lowchen", plural: "Lowchens" },
    {
        key: "norwegian_lundehund",
        type: "dog",
        category: "non_sporting",
        label: "Norwegian Lundehund",
        plural: "Norwegian Lundehunds",
    },
    { key: "poodle", type: "dog", category: "non_sporting", label: "Poodle", plural: "Poodles" },
    { key: "schipperke", type: "dog", category: "non_sporting", label: "Schipperke", plural: "Schipperkes" },
    { key: "shiba_inu", type: "dog", category: "non_sporting", label: "Shiba Inu", plural: "Shiba Inus" },
    {
        key: "tibetan_spaniel",
        type: "dog",
        category: "non_sporting",
        label: "Tibetan Spaniel",
        plural: "Tibetan Spaniels",
    },
    {
        key: "tibetan_terrier",
        type: "dog",
        category: "non_sporting",
        label: "Tibetan Terrier",
        plural: "Tibetan Terriers",
    },
    {
        key: "xoloitzcuintli",
        type: "dog",
        category: "non_sporting",
        label: "Xoloitzcuintli",
        plural: "Xoloitzcuintlis",
    },

    {
        key: "australian_cattle_dog",
        type: "dog",
        category: "herding",
        label: "Australian Cattle Dog",
        plural: "Australian Cattle Dogs",
    },
    {
        key: "australian_shepherd",
        type: "dog",
        category: "herding",
        label: "Australian Shepherd",
        plural: "Australian Shepherds",
    },
    { key: "bearded_collie", type: "dog", category: "herding", label: "Bearded Collie", plural: "Bearded Collies" },
    { key: "beauceron", type: "dog", category: "herding", label: "Beauceron", plural: "Beaucerons" },
    {
        key: "belgian_laekenois",
        type: "dog",
        category: "herding",
        label: "Belgian Laekenois",
        plural: "Belgian Laekenoises",
    },
    {
        key: "belgian_malinois",
        type: "dog",
        category: "herding",
        label: "Belgian Malinois",
        plural: "Belgian Malinois",
    },
    {
        key: "belgian_sheepdog",
        type: "dog",
        category: "herding",
        label: "Belgian Sheepdog",
        plural: "Belgian Sheepdogs",
    },
    {
        key: "belgian_tervuren",
        type: "dog",
        category: "herding",
        label: "Belgian Tervuren",
        plural: "Belgian Tervurens",
    },
    { key: "bergamasco", type: "dog", category: "herding", label: "Bergamasco", plural: "Bergamascos" },
    { key: "berger_picard", type: "dog", category: "herding", label: "Berger Picard", plural: "Berger Picards" },
    { key: "border_collie", type: "dog", category: "herding", label: "Border Collie", plural: "Border Collies" },
    {
        key: "bouvier_des_flanders",
        type: "dog",
        category: "herding",
        label: "Bouvier Des Flanders",
        plural: "Bouviers Des Flanders",
    },
    { key: "briard", type: "dog", category: "herding", label: "Briard", plural: "Briards" },
    { key: "canaan_dog", type: "dog", category: "herding", label: "Canaan Dog", plural: "Canaan Dogs" },
    {
        key: "cardigan_welsh_corgi",
        type: "dog",
        category: "herding",
        label: "Cardigan Welsh Corgi",
        plural: "Cardigan Welsh Corgis",
    },
    { key: "collie", type: "dog", category: "herding", label: "Collie", plural: "Collies" },
    {
        key: "entlebucher_mountain_dog",
        type: "dog",
        category: "herding",
        label: "Entlebucher Mountain Dog",
        plural: "Entlebucher Mountain Dogs",
    },
    {
        key: "finnish_lapphund",
        type: "dog",
        category: "herding",
        label: "Finnish Lapphund",
        plural: "Finnish Lapphunds",
    },
    { key: "german_shepherd", type: "dog", category: "herding", label: "German Shepherd", plural: "German Shepherds" },
    {
        key: "icelandic_sheepdog",
        type: "dog",
        category: "herding",
        label: "Icelandic Sheepdog",
        plural: "Icelandic Sheepdogs",
    },
    {
        key: "lancashire_heeler",
        type: "dog",
        category: "herding",
        label: "Lancashire Heeler",
        plural: "Lancashire Heelers",
    },
    {
        key: "miniature_american_shepherd",
        type: "dog",
        category: "herding",
        label: "Miniature American Shepherd",
        plural: "Miniature American Shepherds",
    },
    { key: "mudi", type: "dog", category: "herding", label: "Mudi", plural: "Mudies" },
    {
        key: "norwegian_buhund",
        type: "dog",
        category: "herding",
        label: "Norwegian Buhund",
        plural: "Norwegian Buhunds",
    },
    {
        key: "old_english_sheepdog",
        type: "dog",
        category: "herding",
        label: "Old English Sheepdog",
        plural: "Old English Sheepdogs",
    },
    {
        key: "pembroke_welsh_corgi",
        type: "dog",
        category: "herding",
        label: "Pembroke Welsh Corgi",
        plural: "Pembroke Welsh Corgis",
    },
    {
        key: "polish_lowland_sheepdog",
        type: "dog",
        category: "herding",
        label: "Polish Lowland Sheepdog",
        plural: "Polish Lowland Sheepdogs",
    },
    { key: "puli", type: "dog", category: "herding", label: "Puli", plural: "Pulis" },
    { key: "pumi", type: "dog", category: "herding", label: "Pumi", plural: "Pumis" },
    {
        key: "pyrenean_shepherd",
        type: "dog",
        category: "herding",
        label: "Pyrenean Shepherd",
        plural: "Pyrenean Shepherds",
    },
    {
        key: "shetland_sheepdog",
        type: "dog",
        category: "herding",
        label: "Shetland Sheepdog",
        plural: "Shetland Sheepdogs",
    },
    {
        key: "spanish_water_dog",
        type: "dog",
        category: "herding",
        label: "Spanish Water Dog",
        plural: "Spanish Water Dogs",
    },
    {
        key: "swedish_vallhund",
        type: "dog",
        category: "herding",
        label: "Swedish Vallhund",
        plural: "Swedish Vallhunds",
    },

    {
        key: "american_shorthair",
        type: "cat",
        category: "short_hair",
        label: "American Shorthair",
        plural: "American Shorthairs",
    },
    {
        key: "british_shorthair",
        type: "cat",
        category: "short_hair",
        label: "British Shorthair",
        plural: "British Shorthairs",
    },
    { key: "burmese", type: "cat", category: "short_hair", label: "Burmese", plural: "Burmese" },
    { key: "russian_blue", type: "cat", category: "short_hair", label: "Russian Blue", plural: "Russian Blues" },
    { key: "siamese", type: "cat", category: "short_hair", label: "Siamese", plural: "Siamese" },
    {
        key: "oriental_shorthair",
        type: "cat",
        category: "short_hair",
        label: "Oriental Shorthair",
        plural: "Oriental Shorthairs",
    },
    { key: "abyssinian", type: "cat", category: "short_hair", label: "Abyssinian", plural: "Abyssinians" },
    { key: "egyptian_mau", type: "cat", category: "short_hair", label: "Egyptian Mau", plural: "Egyptian Maus" },
    { key: "manx", type: "cat", category: "short_hair", label: "Manx", plural: "Manxes" },
    { key: "tonkinese", type: "cat", category: "short_hair", label: "Tonkinese", plural: "Tonkinese" },

    { key: "bengal", type: "cat", category: "medium_hair", label: "Bengal", plural: "Bengals" },
    { key: "scottish_fold", type: "cat", category: "medium_hair", label: "Scottish Fold", plural: "Scottish Folds" },
    {
        key: "norwegian_forest_cat",
        type: "cat",
        category: "medium_hair",
        label: "Norwegian Forest Cat",
        plural: "Norwegian Forest Cats",
    },
    { key: "ragdoll", type: "cat", category: "medium_hair", label: "Ragdoll", plural: "Ragdolls" },
    { key: "somali", type: "cat", category: "medium_hair", label: "Somali", plural: "Somalis" },
    { key: "turkish_van", type: "cat", category: "medium_hair", label: "Turkish Van", plural: "Turkish Vans" },
    {
        key: "japanese_bobtail",
        type: "cat",
        category: "medium_hair",
        label: "Japanese Bobtail",
        plural: "Japanese Bobtails",
    },
    { key: "ocicat", type: "cat", category: "medium_hair", label: "Ocicat", plural: "Ocicats" },
    { key: "balinese", type: "cat", category: "medium_hair", label: "Balinese", plural: "Balinese" },
    { key: "havana_brown", type: "cat", category: "medium_hair", label: "Havana Brown", plural: "Havana Browns" },

    { key: "persian", type: "cat", category: "long_hair", label: "Persian", plural: "Persians" },
    { key: "maine_coon", type: "cat", category: "long_hair", label: "Maine Coon", plural: "Maine Coons" },
    { key: "himalayan", type: "cat", category: "long_hair", label: "Himalayan", plural: "Himalayans" },
    { key: "birman", type: "cat", category: "long_hair", label: "Birman", plural: "Birmans" },
    { key: "siberian", type: "cat", category: "long_hair", label: "Siberian", plural: "Siberians" },
    { key: "ragamuffin", type: "cat", category: "long_hair", label: "Ragamuffin", plural: "Ragamuffins" },
    { key: "turkish_angora", type: "cat", category: "long_hair", label: "Turkish Angora", plural: "Turkish Angoras" },
    {
        key: "chantilly_tiffany",
        type: "cat",
        category: "long_hair",
        label: "Chantilly-Tiffany",
        plural: "Chantilly-Tiffanys",
    },
    {
        key: "somali_longhair",
        type: "cat",
        category: "long_hair",
        label: "Somali Longhair",
        plural: "Somali Longhairs",
    },
    {
        key: "scottish_longhair",
        type: "cat",
        category: "long_hair",
        label: "Scottish Longhair",
        plural: "Scottish Longhairs",
    },

    { key: "sphynx", type: "cat", category: "hairless", label: "Sphynx", plural: "Sphynxes" },
    { key: "peterbald", type: "cat", category: "hairless", label: "Peterbald", plural: "Peterbalds" },
    { key: "donskoy", type: "cat", category: "hairless", label: "Donskoy", plural: "Donskoys" },
    { key: "bambino", type: "cat", category: "hairless", label: "Bambino", plural: "Bambinos" },
    {
        key: "ukrainian_levkoy",
        type: "cat",
        category: "hairless",
        label: "Ukrainian Levkoy",
        plural: "Ukrainian Levkoys",
    },

    {
        key: "american_quarter_horse",
        type: "horse",
        category: "riding",
        label: "American Quarter Horse",
        plural: "American Quarter Horses",
    },
    { key: "thoroughbred", type: "horse", category: "riding", label: "Thoroughbred", plural: "Thoroughbreds" },
    { key: "arabian", type: "horse", category: "riding", label: "Arabian", plural: "Arabians" },
    { key: "appaloosa", type: "horse", category: "riding", label: "Appaloosa", plural: "Appaloosas" },
    { key: "morgan", type: "horse", category: "riding", label: "Morgan", plural: "Morgans" },
    { key: "hanoverian", type: "horse", category: "riding", label: "Hanoverian", plural: "Hanoverians" },
    { key: "trakehner", type: "horse", category: "riding", label: "Trakehner", plural: "Trakehners" },
    { key: "andalusian", type: "horse", category: "riding", label: "Andalusian", plural: "Andalusians" },
    { key: "lusitano", type: "horse", category: "riding", label: "Lusitano", plural: "Lusitanos" },
    { key: "warmblood", type: "horse", category: "riding", label: "Warmblood", plural: "Warmbloods" },

    { key: "clydesdale", type: "horse", category: "working", label: "Clydesdale", plural: "Clydesdales" },
    { key: "percheron", type: "horse", category: "working", label: "Percheron", plural: "Percherons" },
    { key: "belgian", type: "horse", category: "working", label: "Belgian", plural: "Belgians" },
    { key: "shire", type: "horse", category: "working", label: "Shire", plural: "Shires" },
    {
        key: "american_cream_draft",
        type: "horse",
        category: "working",
        label: "American Cream Draft",
        plural: "American Cream Drafts",
    },
    { key: "suffolk_punch", type: "horse", category: "working", label: "Suffolk Punch", plural: "Suffolk Punches" },
    { key: "freiberger", type: "horse", category: "working", label: "Freiberger", plural: "Freibergers" },
    { key: "hackney", type: "horse", category: "working", label: "Hackney", plural: "Hackneys" },
    {
        key: "american_standardbred",
        type: "horse",
        category: "working",
        label: "American Standardbred",
        plural: "American Standardbreds",
    },
    { key: "irish_draught", type: "horse", category: "working", label: "Irish Draught", plural: "Irish Draughts" },

    { key: "shetland_pony", type: "horse", category: "pony", label: "Shetland Pony", plural: "Shetland Ponies" },
    { key: "welsh_pony", type: "horse", category: "pony", label: "Welsh Pony", plural: "Welsh Ponies" },
    { key: "connemara_pony", type: "horse", category: "pony", label: "Connemara Pony", plural: "Connemara Ponies" },
    { key: "fjord_pony", type: "horse", category: "pony", label: "Fjord Pony", plural: "Fjord Ponies" },
    { key: "dartmoor_pony", type: "horse", category: "pony", label: "Dartmoor Pony", plural: "Dartmoor Ponies" },
    { key: "haflinger", type: "horse", category: "pony", label: "Haflinger", plural: "Haflingers" },
    { key: "new_forest_pony", type: "horse", category: "pony", label: "New Forest Pony", plural: "New Forest Ponies" },
    { key: "exmoor_pony", type: "horse", category: "pony", label: "Exmoor Pony", plural: "Exmoor Ponies" },
    {
        key: "chincoteague_pony",
        type: "horse",
        category: "pony",
        label: "Chincoteague Pony",
        plural: "Chincoteague Ponies",
    },
    {
        key: "pony_of_the_americas",
        type: "horse",
        category: "pony",
        label: "Pony of the Americas",
        plural: "Ponies of the Americas",
    },

    {
        key: "miniature_horse",
        type: "horse",
        category: "miniature",
        label: "Miniature Horse",
        plural: "Miniature Horses",
    },
    {
        key: "american_miniature_horse",
        type: "horse",
        category: "miniature",
        label: "American Miniature Horse",
        plural: "American Miniature Horses",
    },
    { key: "falabella", type: "horse", category: "miniature", label: "Falabella", plural: "Falabellas" },
    {
        key: "miniature_shetland",
        type: "horse",
        category: "miniature",
        label: "Miniature Shetland",
        plural: "Miniature Shetlands",
    },
    {
        key: "miniature_appaloosa",
        type: "horse",
        category: "miniature",
        label: "Miniature Appaloosa",
        plural: "Miniature Appaloosas",
    },

    { key: "holstein", type: "livestock", category: "cattle", label: "Holstein", plural: "Holsteins" },
    { key: "angus", type: "livestock", category: "cattle", label: "Angus", plural: "Angus" },
    { key: "hereford", type: "livestock", category: "cattle", label: "Hereford", plural: "Herefords" },
    { key: "jersey", type: "livestock", category: "cattle", label: "Jersey", plural: "Jerseys" },
    { key: "simmental", type: "livestock", category: "cattle", label: "Simmental", plural: "Simmentals" },

    { key: "merino", type: "livestock", category: "sheep", label: "Merino", plural: "Merinos" },
    { key: "suffolk", type: "livestock", category: "sheep", label: "Suffolk", plural: "Suffolks" },
    { key: "dorset", type: "livestock", category: "sheep", label: "Dorset", plural: "Dorsets" },
    { key: "hampshire", type: "livestock", category: "sheep", label: "Hampshire", plural: "Hampshires" },
    { key: "romney", type: "livestock", category: "sheep", label: "Romney", plural: "Romneys" },

    { key: "yorkshire", type: "livestock", category: "pig", label: "Yorkshire", plural: "Yorkshires" },
    { key: "berkshire", type: "livestock", category: "pig", label: "Berkshire", plural: "Berkshires" },
    { key: "duroc", type: "livestock", category: "pig", label: "Duroc", plural: "Durocs" },
    { key: "hampshire", type: "livestock", category: "pig", label: "Hampshire", plural: "Hampshires" },
    { key: "landrace", type: "livestock", category: "pig", label: "Landrace", plural: "Landraces" },

    { key: "nubian", type: "livestock", category: "goat", label: "Nubian", plural: "Nubians" },
    { key: "boer", type: "livestock", category: "goat", label: "Boer", plural: "Boers" },
    { key: "saanen", type: "livestock", category: "goat", label: "Saanen", plural: "Saanens" },
    { key: "alpine", type: "livestock", category: "goat", label: "Alpine", plural: "Alpines" },
    { key: "toggenburg", type: "livestock", category: "goat", label: "Toggenburg", plural: "Toggenburgs" },

    {
        key: "classic_llama",
        type: "livestock",
        category: "llama_alpaca",
        label: "Classic Llama",
        plural: "Classic Llamas",
    },
    { key: "suri_llama", type: "livestock", category: "llama_alpaca", label: "Suri Llama", plural: "Suri Llamas" },
    {
        key: "huacaya_llama",
        type: "livestock",
        category: "llama_alpaca",
        label: "Huacaya Llama",
        plural: "Huacaya Llamas",
    },
    {
        key: "huacaya_alpaca",
        type: "livestock",
        category: "llama_alpaca",
        label: "Huacaya Alpaca",
        plural: "Huacaya Alpacas",
    },
    { key: "suri_alpaca", type: "livestock", category: "llama_alpaca", label: "Suri Alpaca", plural: "Suri Alpacas" },

    {
        key: "rhode_island_red",
        type: "livestock",
        category: "poultry",
        label: "Rhode Island Red",
        plural: "Rhode Island Reds",
    },
    { key: "leghorn", type: "livestock", category: "poultry", label: "Leghorn", plural: "Leghorns" },
    { key: "plymouth_rock", type: "livestock", category: "poultry", label: "Plymouth Rock", plural: "Plymouth Rocks" },
    { key: "sussex", type: "livestock", category: "poultry", label: "Sussex", plural: "Sussex" },
    { key: "orpington", type: "livestock", category: "poultry", label: "Orpington", plural: "Orpingtons" },

    { key: "budgie", type: "small_pet", category: "bird", label: "Budgie", plural: "Budgies" },
    { key: "cockatiel", type: "small_pet", category: "bird", label: "Cockatiel", plural: "Cockatiels" },
    { key: "lovebird", type: "small_pet", category: "bird", label: "Lovebird", plural: "Lovebirds" },
    { key: "parakeet", type: "small_pet", category: "bird", label: "Parakeet", plural: "Parakeets" },
    { key: "canary", type: "small_pet", category: "bird", label: "Canary", plural: "Canaries" },
    { key: "finch", type: "small_pet", category: "bird", label: "Finch", plural: "Finches" },
    {
        key: "african_grey_parrot",
        type: "small_pet",
        category: "bird",
        label: "African Grey Parrot",
        plural: "African Grey Parrots",
    },
    { key: "cockatoo", type: "small_pet", category: "bird", label: "Cockatoo", plural: "Cockatoos" },
    { key: "macaw", type: "small_pet", category: "bird", label: "Macaw", plural: "Macaws" },

    {
        key: "syrian_hamster",
        type: "small_pet",
        category: "hamster",
        label: "Syrian Hamster",
        plural: "Syrian Hamsters",
    },
    {
        key: "roborovski_hamster",
        type: "small_pet",
        category: "hamster",
        label: "Roborovski Hamster",
        plural: "Roborovski Hamsters",
    },
    {
        key: "chinese_hamster",
        type: "small_pet",
        category: "hamster",
        label: "Chinese Hamster",
        plural: "Chinese Hamsters",
    },

    { key: "holland_lop", type: "small_pet", category: "bunny", label: "Holland Lop", plural: "Holland Lops" },
    {
        key: "netherland_dwarf",
        type: "small_pet",
        category: "bunny",
        label: "Netherland Dwarf",
        plural: "Netherland Dwarfs",
    },
    { key: "lionhead", type: "small_pet", category: "bunny", label: "Lionhead", plural: "Lionheads" },
    { key: "mini_rex", type: "small_pet", category: "bunny", label: "Mini Rex", plural: "Mini Rexes" },
    { key: "flemish_giant", type: "small_pet", category: "bunny", label: "Flemish Giant", plural: "Flemish Giants" },

    { key: "american", type: "small_pet", category: "guinea_pig", label: "American", plural: "Americans" },
    { key: "abyssinian", type: "small_pet", category: "guinea_pig", label: "Abyssinian", plural: "Abyssinians" },
    { key: "peruvian", type: "small_pet", category: "guinea_pig", label: "Peruvian", plural: "Peruvians" },
    { key: "sheltie", type: "small_pet", category: "guinea_pig", label: "Sheltie", plural: "Shelties" },
    { key: "teddy", type: "small_pet", category: "guinea_pig", label: "Teddy", plural: "Teddies" },

    { key: "fancy_mouse", type: "small_pet", category: "mouse", label: "Fancy Mouse", plural: "Fancy Mice" },
    { key: "burmese_mouse", type: "small_pet", category: "mouse", label: "Burmese Mouse", plural: "Burmese Mice" },
    { key: "satin_mouse", type: "small_pet", category: "mouse", label: "Satin Mouse", plural: "Satin Mice" },

    { key: "standard_rat", type: "small_pet", category: "rat", label: "Standard Rat", plural: "Standard Rats" },
    { key: "dumbo_rat", type: "small_pet", category: "rat", label: "Dumbo Rat", plural: "Dumbo Rats" },
    { key: "hairless_rat", type: "small_pet", category: "rat", label: "Hairless Rat", plural: "Hairless Rats" },

    {
        key: "standard_ferret",
        type: "small_pet",
        category: "ferret",
        label: "Standard Ferret",
        plural: "Standard Ferrets",
    },
    { key: "albino_ferret", type: "small_pet", category: "ferret", label: "Albino Ferret", plural: "Albino Ferrets" },
    { key: "sable_ferret", type: "small_pet", category: "ferret", label: "Sable Ferret", plural: "Sable Ferrets" },
    { key: "silver_ferret", type: "small_pet", category: "ferret", label: "Silver Ferret", plural: "Silver Ferrets" },

    { key: "wildlife", type: "other", category: "wildlife", label: "Wildlife", plural: "Wildlife" },
    { key: "exotic", type: "other", category: "exotic", label: "Exotic", plural: "Exotics" },
];
