// Animal Breeds Module
export const animalBreeds = {
  sporting: [
    "American Water Spaniel",
    "Barbet",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Brittany",
    "Chesapeake Bay Retriever",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Curly-Coated Retriever",
    "English Cocker Spaniel",
    "English Setter",
    "English Springer Spaniel",
    "Field Spaniel",
    "Flat-Coated Retriever",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Golden Retriever",
    "Gordon Setter",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Water Spaniel",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Nederlandse Kooikerhondje",
    "Nova Scotia Duck Tolling Retriever",
    "Pointer",
    "Spinone Italiano",
    "Sussex Spaniel",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "Wirehaired Pointing Griffon",
    "Wirehaired Vizsla",
    "Other",
  ],
  hound: [
    "Afghan Hound",
    "American English Coonhound",
    "American Foxhound",
    "Azawakh",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Black and Tan Coonhound",
    "Bloodhound",
    "Bluetick Coonhound",
    "Borzoi",
    "Cirneco dell’Etna",
    "Dachshund",
    "English Foxhound",
    "Grand Basset Griffon Vendeen",
    "Greyhound",
    "Harrier",
    "Ibizan Hound",
    "Irish Wolfhound",
    "Norwegian Elkhound",
    "Otterhound",
    "Petit Basset Griffon Vendeen",
    "Pharaoh Hound",
    "Plott Hound",
    "Portuguese Podengo Pequeno",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Saluki",
    "Scottish Deerhound",
    "Sloughi",
    "Treeing Walker Coonhound",
    "Whippet",
    "Other",
  ],
  working: [
    "Akita",
    "Alaskan Malamute",
    "Anatolian Shepherd Dog",
    "Bernese Mountain Dog",
    "Black Russian Terrier",
    "Boerboel",
    "Boxer",
    "Bullmastiff",
    "Cane Corso",
    "Chinook",
    "Danish-Swedish Farmdog",
    "Doberman Pinscher",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "German Pinscher",
    "Giant Schnauzer",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Komondor",
    "Kuvasz",
    "Leonberger",
    "Mastiff",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Portuguese Water Dog",
    "Rottweiler",
    "St. Bernard",
    "Samoyed",
    "Siberian Husky",
    "Standard Schnauzer",
    "Tibetan Mastiff",
    "Other",
  ],
  terrier: [
    "Airedale Terrier",
    "American Hairless Terrier",
    "American Staffordshire Terrier",
    "Australian Terrier",
    "Bedlington Terrier",
    "Border Terrier",
    "Bull Terrier",
    "Cairn Terrier",
    "Cesky Terrier",
    "Dandie Dinmont Terrier",
    "Glen of Imaal Terrier",
    "Irish Terrier",
    "Kerry Blue Terrier",
    "Lakeland Terrier",
    "Manchester Terrier",
    "Miniature Bull Terrier",
    "Miniature Schnauzer",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Parson Russell Terrier",
    "Rat Terrier",
    "Russell Terrier",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Skye Terrier",
    "Smooth Fox Terrier",
    "Soft Coated Wheaton Terrier",
    "Staffordshire Bull Terrier",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Wire Fox Terrier",
    "Other",
  ],
  toy: [
    "Affenpinscher",
    "Biewer Terrier",
    "Brussels Griffon",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chinese Crested",
    "English Toy Spaniel",
    "Havanese",
    "Italian Greyhound",
    "Japanese Chin",
    "Maltese",
    "Manchester Terrier",
    "Miniature Pinscher",
    "Papillon",
    "Pekingese",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Russian Toy",
    "Shih Tzu",
    "Silky Terrier",
    "Toy Fox Terrier",
    "Yorkshire Terrier",
    "Other",
  ],
  non_sporting: [
    "American Eskimo Dog",
    "Bichon Frise",
    "Boston Terrier",
    "Bulldog",
    "Chinese Shar-Pei",
    "Chow Chow",
    "Coton de Tulear",
    "Dalmatian",
    "Finnish Spitz",
    "French Bulldog",
    "Keeshond",
    "Lhasa Apso",
    "Lowchen",
    "Norwegian Lundehund",
    "Poodle",
    "Schipperke",
    "Shiba Inu",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Xoloitzcuintli",
    "Other",
  ],
  herding: [
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Bearded Collie",
    "Beauceron",
    "Belgian Laekenois",
    "Belgian Malinois",
    "Belgian Sheepdog",
    "Belgian Tervuren",
    "Bergamasco",
    "Berger Picard",
    "Border Collie",
    "Bouvier Des Flanders",
    "Briard",
    "Canaan Dog",
    "Cardigan Welsh Corgi",
    "Collie",
    "Entlebucher Mountain Dog",
    "Finnish Lapphund",
    "German Shepherd Dog",
    "Icelandic Sheepdog",
    "Lancashire Heeler",
    "Miniature American Shepherd",
    "Mudi",
    "Norwegian Buhund",
    "Old English Sheepdog",
    "Pembroke Welsh Corgi",
    "Polish Lowland Sheepdog",
    "Puli",
    "Pumi",
    "Pyrenean Shepherd",
    "Shetland Sheepdog",
    "Spanish Water Dog",
    "Swedish Vallhund",
    "Other",
  ],
  other: ["Other"],
};
