export const dummyAnimals = {
  dogs: [
    { id: 1, name: "Buddy" },
    { id: 2, name: "Luna" },
    { id: 3, name: "Max" },
    { id: 4, name: "Bella" },
    { id: 5, name: "Charlie" },
    { id: 6, name: "Lucy" },
    { id: 7, name: "Cooper" },
    { id: 8, name: "Daisy" },
    { id: 9, name: "Rocky" },
  ],
  cats: [
    { id: 10, name: "Mittens" },
    { id: 11, name: "Shadow" },
    { id: 12, name: "Simba" },
    { id: 13, name: "Luna" },
    { id: 14, name: "Oreo" },
    { id: 15, name: "Cleo" },
    { id: 16, name: "Tiger" },
    { id: 17, name: "Nala" },
  ],
  horses: [
    { id: 18, name: "Star" },
    { id: 19, name: "Blaze" },
    { id: 20, name: "Spirit" },
    { id: 21, name: "Willow" },
    { id: 22, name: "Thunder" },
    { id: 23, name: "Rose" },
  ],
  livestock: [
    { id: 24, name: "Bessie" },
    { id: 25, name: "Angus" },
    { id: 26, name: "Dolly" },
    { id: 27, name: "Spot" },
    { id: 28, name: "Clover" },
    { id: 29, name: "Rusty" },
    { id: 30, name: "Maple" },
  ],
  wildlife: [
    { id: 31, name: "Fox" },
    { id: 32, name: "Deer" },
    { id: 33, name: "Raven" },
    { id: 34, name: "Otter" },
    { id: 35, name: "Hawk" },
    { id: 36, name: "Badger" },
  ],
  exotic: [
    { id: 37, name: "Zara the Zebra" },
    { id: 38, name: "Kumo the Koala" },
    { id: 39, name: "Rafi the Giraffe" },
    { id: 40, name: "Tango the Tiger" },
    { id: 41, name: "Lulu the Lemur" },
    { id: 42, name: "Nico the Macaw" },
    { id: 43, name: "Paco the Parrot" },
    { id: 44, name: "Suki the Sloth" },
    { id: 45, name: "Kaya the Kangaroo" },
    { id: 46, name: "Ollie the Orangutan" },
  ],
};
