export function getAnimalBreeds({ type, category, id } = {}) {
    const matchingBreeds = animalBreeds.filter(
        (breed) =>
            (!type || breed.type === type) && (!category || breed.category === category) && (!id || breed.id === id),
    );
    return id ? matchingBreeds[0] : matchingBreeds;
}

const animalBreeds = [
    {
        id: "american_water_spaniel",
        type: "dog",
        category: "sporting",
        label: "American Water Spaniel",
        plural: "American Water Spaniels",
        url: "/animals/",
    },
    { id: "barbet", type: "dog", category: "sporting", label: "Barbet", plural: "Barbets", url: "/animals/" },
    {
        id: "boykin_spaniel",
        type: "dog",
        category: "sporting",
        label: "Boykin Spaniel",
        plural: "Boykin Spaniels",
        url: "/animals/",
    },
    {
        id: "bracco_italiano",
        type: "dog",
        category: "sporting",
        label: "Bracco Italiano",
        plural: "Bracco Italianos",
        url: "/animals/",
    },
    { id: "brittany", type: "dog", category: "sporting", label: "Brittany", plural: "Brittanies", url: "/animals/" },
    {
        id: "chesapeake_bay_retriever",
        type: "dog",
        category: "sporting",
        label: "Chesapeake Bay Retriever",
        plural: "Chesapeake Bay Retrievers",
        url: "/animals/",
    },
    {
        id: "clumber_spaniel",
        type: "dog",
        category: "sporting",
        label: "Clumber Spaniel",
        plural: "Clumber Spaniels",
        url: "/animals/",
    },
    {
        id: "cocker_spaniel",
        type: "dog",
        category: "sporting",
        label: "Cocker Spaniel",
        plural: "Cocker Spaniels",
        url: "/animals/",
    },
    {
        id: "curly_coated_retriever",
        type: "dog",
        category: "sporting",
        label: "Curly-Coated Retriever",
        plural: "Curly-Coated Retrievers",
        url: "/animals/",
    },
    {
        id: "english_cocker_spaniel",
        type: "dog",
        category: "sporting",
        label: "English Cocker Spaniel",
        plural: "English Cocker Spaniels",
        url: "/animals/",
    },
    {
        id: "english_setter",
        type: "dog",
        category: "sporting",
        label: "English Setter",
        plural: "English Setters",
        url: "/animals/",
    },
    {
        id: "english_springer_spaniel",
        type: "dog",
        category: "sporting",
        label: "English Springer Spaniel",
        plural: "English Springer Spaniels",
        url: "/animals/",
    },
    {
        id: "field_spaniel",
        type: "dog",
        category: "sporting",
        label: "Field Spaniel",
        plural: "Field Spaniels",
        url: "/animals/",
    },
    {
        id: "flat_coated_retriever",
        type: "dog",
        category: "sporting",
        label: "Flat-Coated Retriever",
        plural: "Flat-Coated Retrievers",
        url: "/animals/",
    },
    {
        id: "german_shorthaired_pointer",
        type: "dog",
        category: "sporting",
        label: "German Shorthaired Pointer",
        plural: "German Shorthaired Pointers",
        url: "/animals/",
    },
    {
        id: "german_wirehaired_pointer",
        type: "dog",
        category: "sporting",
        label: "German Wirehaired Pointer",
        plural: "German Wirehaired Pointers",
        url: "/animals/",
    },
    {
        id: "golden_retriever",
        type: "dog",
        category: "sporting",
        label: "Golden Retriever",
        plural: "Golden Retrievers",
        url: "/animals/",
    },
    {
        id: "gordon_setter",
        type: "dog",
        category: "sporting",
        label: "Gordon Setter",
        plural: "Gordon Setters",
        url: "/animals/",
    },
    {
        id: "irish_red_and_white_setter",
        type: "dog",
        category: "sporting",
        label: "Irish Red and White Setter",
        plural: "Irish Red and White Setters",
        url: "/animals/",
    },
    {
        id: "irish_setter",
        type: "dog",
        category: "sporting",
        label: "Irish Setter",
        plural: "Irish Setters",
        url: "/animals/",
    },
    {
        id: "irish_water_spaniel",
        type: "dog",
        category: "sporting",
        label: "Irish Water Spaniel",
        plural: "Irish Water Spaniels",
        url: "/animals/",
    },
    {
        id: "labrador_retriever",
        type: "dog",
        category: "sporting",
        label: "Labrador Retriever",
        plural: "Labrador Retrievers",
        url: "/animals/",
    },
    {
        id: "lagotto_romagnolo",
        type: "dog",
        category: "sporting",
        label: "Lagotto Romagnolo",
        plural: "Lagotto Romagnolos",
        url: "/animals/",
    },
    {
        id: "nederlandse_kooikerhondje",
        type: "dog",
        category: "sporting",
        label: "Nederlandse Kooikerhondje",
        plural: "Nederlandse Kooikerhondjes",
        url: "/animals/",
    },
    {
        id: "nova_scotia_duck_tolling_retriever",
        type: "dog",
        category: "sporting",
        label: "Nova Scotia Duck Tolling Retriever",
        plural: "Nova Scotia Duck Tolling Retrievers",
        url: "/animals/",
    },
    { id: "pointer", type: "dog", category: "sporting", label: "Pointer", plural: "Pointers", url: "/animals/" },
    {
        id: "spinone_italiano",
        type: "dog",
        category: "sporting",
        label: "Spinone Italiano",
        plural: "Spinone Italianos",
        url: "/animals/",
    },
    {
        id: "sussex_spaniel",
        type: "dog",
        category: "sporting",
        label: "Sussex Spaniel",
        plural: "Sussex Spaniels",
        url: "/animals/",
    },
    { id: "vizsla", type: "dog", category: "sporting", label: "Vizsla", plural: "Vizslas", url: "/animals/" },
    {
        id: "weimaraner",
        type: "dog",
        category: "sporting",
        label: "Weimaraner",
        plural: "Weimaraners",
        url: "/animals/",
    },
    {
        id: "welsh_springer_spaniel",
        type: "dog",
        category: "sporting",
        label: "Welsh Springer Spaniel",
        plural: "Welsh Springer Spaniels",
        url: "/animals/",
    },
    {
        id: "wirehaired_pointing_griffon",
        type: "dog",
        category: "sporting",
        label: "Wirehaired Pointing Griffon",
        plural: "Wirehaired Pointing Griffons",
        url: "/animals/",
    },
    {
        id: "wirehaired_vizsla",
        type: "dog",
        category: "sporting",
        label: "Wirehaired Vizsla",
        plural: "Wirehaired Vizslas",
        url: "/animals/",
    },
    {
        id: "afghan_hound",
        type: "dog",
        category: "hound",
        label: "Afghan Hound",
        plural: "Afghan Hounds",
        url: "/animals/",
    },
    {
        id: "american_english_coonhound",
        type: "dog",
        category: "hound",
        label: "American English Coonhound",
        plural: "American English Coonhounds",
        url: "/animals/",
    },
    {
        id: "american_foxhound",
        type: "dog",
        category: "hound",
        label: "American Foxhound",
        plural: "American Foxhounds",
        url: "/animals/",
    },
    { id: "azawakh", type: "dog", category: "hound", label: "Azawakh", plural: "Azawakhs", url: "/animals/" },
    { id: "basenji", type: "dog", category: "hound", label: "Basenji", plural: "Basenjis", url: "/animals/" },
    {
        id: "basset_hound",
        type: "dog",
        category: "hound",
        label: "Basset Hound",
        plural: "Basset Hounds",
        url: "/animals/",
    },
    { id: "beagle", type: "dog", category: "hound", label: "Beagle", plural: "Beagles", url: "/animals/" },
    {
        id: "black_and_tan_coonhound",
        type: "dog",
        category: "hound",
        label: "Black and Tan Coonhound",
        plural: "Black and Tan Coonhounds",
        url: "/animals/",
    },
    { id: "bloodhound", type: "dog", category: "hound", label: "Bloodhound", plural: "Bloodhounds", url: "/animals/" },
    {
        id: "bluetick_coonhound",
        type: "dog",
        category: "hound",
        label: "Bluetick Coonhound",
        plural: "Bluetick Coonhounds",
        url: "/animals/",
    },
    { id: "borzoi", type: "dog", category: "hound", label: "Borzoi", plural: "Borzoi", url: "/animals/" },
    {
        id: "cirneco_dell_etna",
        type: "dog",
        category: "hound",
        label: "Cirneco dell’Etna",
        plural: "Cirneco dell’Etnas",
        url: "/animals/",
    },
    { id: "dachshund", type: "dog", category: "hound", label: "Dachshund", plural: "Dachshunds", url: "/animals/" },
    {
        id: "english_foxhound",
        type: "dog",
        category: "hound",
        label: "English Foxhound",
        plural: "English Foxhounds",
        url: "/animals/",
    },
    {
        id: "grand_basset_griffon_vendeen",
        type: "dog",
        category: "hound",
        label: "Grand Basset Griffon Vendeen",
        plural: "Grand Basset Griffon Vendeens",
        url: "/animals/",
    },
    { id: "greyhound", type: "dog", category: "hound", label: "Greyhound", plural: "Greyhounds", url: "/animals/" },
    { id: "harrier", type: "dog", category: "hound", label: "Harrier", plural: "Harriers", url: "/animals/" },
    {
        id: "ibizan_hound",
        type: "dog",
        category: "hound",
        label: "Ibizan Hound",
        plural: "Ibizan Hounds",
        url: "/animals/",
    },
    {
        id: "irish_wolfhound",
        type: "dog",
        category: "hound",
        label: "Irish Wolfhound",
        plural: "Irish Wolfhounds",
        url: "/animals/",
    },
    {
        id: "norwegian_elkhound",
        type: "dog",
        category: "hound",
        label: "Norwegian Elkhound",
        plural: "Norwegian Elkhounds",
        url: "/animals/",
    },
    { id: "otterhound", type: "dog", category: "hound", label: "Otterhound", plural: "Otterhounds", url: "/animals/" },
    {
        id: "petit_basset_griffon_vendeen",
        type: "dog",
        category: "hound",
        label: "Petit Basset Griffon Vendeen",
        plural: "Petit Basset Griffon Vendeens",
        url: "/animals/",
    },
    {
        id: "pharaoh_hound",
        type: "dog",
        category: "hound",
        label: "Pharaoh Hound",
        plural: "Pharaoh Hounds",
        url: "/animals/",
    },
    {
        id: "plott_hound",
        type: "dog",
        category: "hound",
        label: "Plott Hound",
        plural: "Plott Hounds",
        url: "/animals/",
    },
    {
        id: "portuguese_podengo_pequeno",
        type: "dog",
        category: "hound",
        label: "Portuguese Podengo Pequeno",
        plural: "Portuguese Podengo Pequenos",
        url: "/animals/",
    },
    {
        id: "redbone_coonhound",
        type: "dog",
        category: "hound",
        label: "Redbone Coonhound",
        plural: "Redbone Coonhounds",
        url: "/animals/",
    },
    {
        id: "rhodesian_ridgeback",
        type: "dog",
        category: "hound",
        label: "Rhodesian Ridgeback",
        plural: "Rhodesian Ridgebacks",
        url: "/animals/",
    },
    { id: "saluki", type: "dog", category: "hound", label: "Saluki", plural: "Salukis", url: "/animals/" },
    {
        id: "scottish_deerhound",
        type: "dog",
        category: "hound",
        label: "Scottish Deerhound",
        plural: "Scottish Deerhounds",
        url: "/animals/",
    },
    { id: "sloughi", type: "dog", category: "hound", label: "Sloughi", plural: "Sloughis", url: "/animals/" },
    {
        id: "treeing_walker_coonhound",
        type: "dog",
        category: "hound",
        label: "Treeing Walker Coonhound",
        plural: "Treeing Walker Coonhounds",
        url: "/animals/",
    },
    { id: "whippet", type: "dog", category: "hound", label: "Whippet", plural: "Whippets", url: "/animals/" },

    { id: "akita", type: "dog", category: "working_dog", label: "Akita", plural: "Akitas", url: "/animals/" },
    {
        id: "alaskan_malamute",
        type: "dog",
        category: "working_dog",
        label: "Alaskan Malamute",
        plural: "Alaskan Malamutes",
        url: "/animals/",
    },
    {
        id: "anatolian_shepherd_dog",
        type: "dog",
        category: "working_dog",
        label: "Anatolian Shepherd Dog",
        plural: "Anatolian Shepherd Dogs",
        url: "/animals/",
    },
    {
        id: "bernese_mountain_dog",
        type: "dog",
        category: "working_dog",
        label: "Bernese Mountain Dog",
        plural: "Bernese Mountain Dogs",
        url: "/animals/",
    },
    {
        id: "black_russian_terrier",
        type: "dog",
        category: "working_dog",
        label: "Black Russian Terrier",
        plural: "Black Russian Terriers",
        url: "/animals/",
    },
    { id: "boerboel", type: "dog", category: "working_dog", label: "Boerboel", plural: "Boerboels", url: "/animals/" },
    { id: "boxer", type: "dog", category: "working_dog", label: "Boxer", plural: "Boxers", url: "/animals/" },
    {
        id: "bullmastiff",
        type: "dog",
        category: "working_dog",
        label: "Bullmastiff",
        plural: "Bullmastiffs",
        url: "/animals/",
    },
    {
        id: "cane_corso",
        type: "dog",
        category: "working_dog",
        label: "Cane Corso",
        plural: "Cane Corsos",
        url: "/animals/",
    },
    { id: "chinook", type: "dog", category: "working_dog", label: "Chinook", plural: "Chinooks", url: "/animals/" },
    {
        id: "danish_swedish_farmdog",
        type: "dog",
        category: "working_dog",
        label: "Danish-Swedish Farmdog",
        plural: "Danish-Swedish Farmdogs",
        url: "/animals/",
    },
    {
        id: "doberman_pinscher",
        type: "dog",
        category: "working_dog",
        label: "Doberman Pinscher",
        plural: "Doberman Pinschers",
        url: "/animals/",
    },
    {
        id: "dogo_argentino",
        type: "dog",
        category: "working_dog",
        label: "Dogo Argentino",
        plural: "Dogo Argentinos",
        url: "/animals/",
    },
    {
        id: "dogue_de_bordeaux",
        type: "dog",
        category: "working_dog",
        label: "Dogue de Bordeaux",
        plural: "Dogues de Bordeaux",
        url: "/animals/",
    },
    {
        id: "german_pinscher",
        type: "dog",
        category: "working_dog",
        label: "German Pinscher",
        plural: "German Pinschers",
        url: "/animals/",
    },
    {
        id: "giant_schnauzer",
        type: "dog",
        category: "working_dog",
        label: "Giant Schnauzer",
        plural: "Giant Schnauzers",
        url: "/animals/",
    },
    {
        id: "great_dane",
        type: "dog",
        category: "working_dog",
        label: "Great Dane",
        plural: "Great Danes",
        url: "/animals/",
    },
    {
        id: "great_pyrenees",
        type: "dog",
        category: "working_dog",
        label: "Great Pyrenees",
        plural: "Great Pyrenees",
        url: "/animals/",
    },
    {
        id: "greater_swiss_mountain_dog",
        type: "dog",
        category: "working_dog",
        label: "Greater Swiss Mountain Dog",
        plural: "Greater Swiss Mountain Dogs",
        url: "/animals/",
    },
    { id: "komondor", type: "dog", category: "working_dog", label: "Komondor", plural: "Komondors", url: "/animals/" },
    { id: "kuvasz", type: "dog", category: "working_dog", label: "Kuvasz", plural: "Kuvasz", url: "/animals/" },
    {
        id: "leonberger",
        type: "dog",
        category: "working_dog",
        label: "Leonberger",
        plural: "Leonbergers",
        url: "/animals/",
    },
    { id: "mastiff", type: "dog", category: "working_dog", label: "Mastiff", plural: "Mastiffs", url: "/animals/" },
    {
        id: "neapolitan_mastiff",
        type: "dog",
        category: "working_dog",
        label: "Neapolitan Mastiff",
        plural: "Neapolitan Mastiffs",
        url: "/animals/",
    },
    {
        id: "newfoundland",
        type: "dog",
        category: "working_dog",
        label: "Newfoundland",
        plural: "Newfoundlands",
        url: "/animals/",
    },
    {
        id: "portuguese_water_dog",
        type: "dog",
        category: "working_dog",
        label: "Portuguese Water Dog",
        plural: "Portuguese Water Dogs",
        url: "/animals/",
    },
    {
        id: "rottweiler",
        type: "dog",
        category: "working_dog",
        label: "Rottweiler",
        plural: "Rottweilers",
        url: "/animals/",
    },
    {
        id: "st_bernard",
        type: "dog",
        category: "working_dog",
        label: "St. Bernard",
        plural: "St. Bernards",
        url: "/animals/",
    },
    { id: "samoyed", type: "dog", category: "working_dog", label: "Samoyed", plural: "Samoyeds", url: "/animals/" },
    {
        id: "siberian_husky",
        type: "dog",
        category: "working_dog",
        label: "Siberian Husky",
        plural: "Siberian Huskies",
        url: "/animals/",
    },
    {
        id: "standard_schnauzer",
        type: "dog",
        category: "working_dog",
        label: "Standard Schnauzer",
        plural: "Standard Schnauzers",
        url: "/animals/",
    },
    {
        id: "tibetan_mastiff",
        type: "dog",
        category: "working_dog",
        label: "Tibetan Mastiff",
        plural: "Tibetan Mastiffs",
        url: "/animals/",
    },

    {
        id: "airedale_terrier",
        type: "dog",
        category: "terrier",
        label: "Airedale Terrier",
        plural: "Airedale Terriers",
        url: "/animals/",
    },
    {
        id: "american_hairless_terrier",
        type: "dog",
        category: "terrier",
        label: "American Hairless Terrier",
        plural: "American Hairless Terriers",
        url: "/animals/",
    },
    {
        id: "american_staffordshire_terrier",
        type: "dog",
        category: "terrier",
        label: "American Staffordshire Terrier",
        plural: "American Staffordshire Terriers",
        url: "/animals/",
    },
    {
        id: "australian_terrier",
        type: "dog",
        category: "terrier",
        label: "Australian Terrier",
        plural: "Australian Terriers",
        url: "/animals/",
    },
    {
        id: "bedlington_terrier",
        type: "dog",
        category: "terrier",
        label: "Bedlington Terrier",
        plural: "Bedlington Terriers",
        url: "/animals/",
    },
    {
        id: "border_terrier",
        type: "dog",
        category: "terrier",
        label: "Border Terrier",
        plural: "Border Terriers",
        url: "/animals/",
    },
    {
        id: "bull_terrier",
        type: "dog",
        category: "terrier",
        label: "Bull Terrier",
        plural: "Bull Terriers",
        url: "/animals/",
    },
    {
        id: "cairn_terrier",
        type: "dog",
        category: "terrier",
        label: "Cairn Terrier",
        plural: "Cairn Terriers",
        url: "/animals/",
    },
    {
        id: "cesky_terrier",
        type: "dog",
        category: "terrier",
        label: "Cesky Terrier",
        plural: "Cesky Terriers",
        url: "/animals/",
    },
    {
        id: "dandie_dinmont_terrier",
        type: "dog",
        category: "terrier",
        label: "Dandie Dinmont Terrier",
        plural: "Dandie Dinmont Terriers",
        url: "/animals/",
    },
    {
        id: "glen_of_imaal_terrier",
        type: "dog",
        category: "terrier",
        label: "Glen of Imaal Terrier",
        plural: "Glen of Imaal Terriers",
        url: "/animals/",
    },
    {
        id: "irish_terrier",
        type: "dog",
        category: "terrier",
        label: "Irish Terrier",
        plural: "Irish Terriers",
        url: "/animals/",
    },
    {
        id: "kerry_blue_terrier",
        type: "dog",
        category: "terrier",
        label: "Kerry Blue Terrier",
        plural: "Kerry Blue Terriers",
        url: "/animals/",
    },
    {
        id: "lakeland_terrier",
        type: "dog",
        category: "terrier",
        label: "Lakeland Terrier",
        plural: "Lakeland Terriers",
        url: "/animals/",
    },
    {
        id: "manchester_terrier",
        type: "dog",
        category: "terrier",
        label: "Manchester Terrier",
        plural: "Manchester Terriers",
        url: "/animals/",
    },
    {
        id: "miniature_bull_terrier",
        type: "dog",
        category: "terrier",
        label: "Miniature Bull Terrier",
        plural: "Miniature Bull Terriers",
        url: "/animals/",
    },
    {
        id: "miniature_schnauzer",
        type: "dog",
        category: "terrier",
        label: "Miniature Schnauzer",
        plural: "Miniature Schnauzers",
        url: "/animals/",
    },
    {
        id: "norfolk_terrier",
        type: "dog",
        category: "terrier",
        label: "Norfolk Terrier",
        plural: "Norfolk Terriers",
        url: "/animals/",
    },
    {
        id: "norwich_terrier",
        type: "dog",
        category: "terrier",
        label: "Norwich Terrier",
        plural: "Norwich Terriers",
        url: "/animals/",
    },
    {
        id: "parson_russell_terrier",
        type: "dog",
        category: "terrier",
        label: "Parson Russell Terrier",
        plural: "Parson Russell Terriers",
        url: "/animals/",
    },
    {
        id: "rat_terrier",
        type: "dog",
        category: "terrier",
        label: "Rat Terrier",
        plural: "Rat Terriers",
        url: "/animals/",
    },
    {
        id: "russell_terrier",
        type: "dog",
        category: "terrier",
        label: "Russell Terrier",
        plural: "Russell Terriers",
        url: "/animals/",
    },
    {
        id: "scottish_terrier",
        type: "dog",
        category: "terrier",
        label: "Scottish Terrier",
        plural: "Scottish Terriers",
        url: "/animals/",
    },
    {
        id: "sealyham_terrier",
        type: "dog",
        category: "terrier",
        label: "Sealyham Terrier",
        plural: "Sealyham Terriers",
        url: "/animals/",
    },
    {
        id: "skye_terrier",
        type: "dog",
        category: "terrier",
        label: "Skye Terrier",
        plural: "Skye Terriers",
        url: "/animals/",
    },
    {
        id: "smooth_fox_terrier",
        type: "dog",
        category: "terrier",
        label: "Smooth Fox Terrier",
        plural: "Smooth Fox Terriers",
        url: "/animals/",
    },
    {
        id: "soft_coated_wheaton_terrier",
        type: "dog",
        category: "terrier",
        label: "Soft Coated Wheaton Terrier",
        plural: "Soft Coated Wheaton Terriers",
        url: "/animals/",
    },
    {
        id: "staffordshire_bull_terrier",
        type: "dog",
        category: "terrier",
        label: "Staffordshire Bull Terrier",
        plural: "Staffordshire Bull Terriers",
        url: "/animals/",
    },
    {
        id: "welsh_terrier",
        type: "dog",
        category: "terrier",
        label: "Welsh Terrier",
        plural: "Welsh Terriers",
        url: "/animals/",
    },
    {
        id: "west_highland_white_terrier",
        type: "dog",
        category: "terrier",
        label: "West Highland White Terrier",
        plural: "West Highland White Terriers",
        url: "/animals/",
    },
    {
        id: "wire_fox_terrier",
        type: "dog",
        category: "terrier",
        label: "Wire Fox Terrier",
        plural: "Wire Fox Terriers",
        url: "/animals/",
    },

    {
        id: "affenpinscher",
        type: "dog",
        category: "toy",
        label: "Affenpinscher",
        plural: "Affenpinschers",
        url: "/animals/",
    },
    {
        id: "biewer_terrier",
        type: "dog",
        category: "toy",
        label: "Biewer Terrier",
        plural: "Biewer Terriers",
        url: "/animals/",
    },
    {
        id: "brussels_griffon",
        type: "dog",
        category: "toy",
        label: "Brussels Griffon",
        plural: "Brussels Griffons",
        url: "/animals/",
    },
    {
        id: "cavalier_king_charles_spaniel",
        type: "dog",
        category: "toy",
        label: "Cavalier King Charles Spaniel",
        plural: "Cavalier King Charles Spaniels",
        url: "/animals/",
    },
    { id: "chihuahua", type: "dog", category: "toy", label: "Chihuahua", plural: "Chihuahuas", url: "/animals/" },
    {
        id: "chinese_crested",
        type: "dog",
        category: "toy",
        label: "Chinese Crested",
        plural: "Chinese Cresteds",
        url: "/animals/",
    },
    {
        id: "english_toy_spaniel",
        type: "dog",
        category: "toy",
        label: "English Toy Spaniel",
        plural: "English Toy Spaniels",
        url: "/animals/",
    },
    { id: "havanese", type: "dog", category: "toy", label: "Havanese", plural: "Havanese", url: "/animals/" },
    {
        id: "italian_greyhound",
        type: "dog",
        category: "toy",
        label: "Italian Greyhound",
        plural: "Italian Greyhounds",
        url: "/animals/",
    },
    {
        id: "japanese_chin",
        type: "dog",
        category: "toy",
        label: "Japanese Chin",
        plural: "Japanese Chins",
        url: "/animals/",
    },
    { id: "maltese", type: "dog", category: "toy", label: "Maltese", plural: "Malteses", url: "/animals/" },
    {
        id: "manchester_terrier",
        type: "dog",
        category: "toy",
        label: "Manchester Terrier",
        plural: "Manchester Terriers",
        url: "/animals/",
    },
    {
        id: "miniature_pinscher",
        type: "dog",
        category: "toy",
        label: "Miniature Pinscher",
        plural: "Miniature Pinschers",
        url: "/animals/",
    },
    { id: "papillon", type: "dog", category: "toy", label: "Papillon", plural: "Papillons", url: "/animals/" },
    { id: "pekingese", type: "dog", category: "toy", label: "Pekingese", plural: "Pekingese", url: "/animals/" },
    { id: "pomeranian", type: "dog", category: "toy", label: "Pomeranian", plural: "Pomeranians", url: "/animals/" },
    { id: "poodle", type: "dog", category: "toy", label: "Poodle", plural: "Poodles", url: "/animals/" },
    { id: "pug", type: "dog", category: "toy", label: "Pug", plural: "Pugs", url: "/animals/" },
    { id: "russian_toy", type: "dog", category: "toy", label: "Russian Toy", plural: "Russian Toys", url: "/animals/" },
    { id: "shih_tzu", type: "dog", category: "toy", label: "Shih Tzu", plural: "Shih Tzus", url: "/animals/" },
    {
        id: "silky_terrier",
        type: "dog",
        category: "toy",
        label: "Silky Terrier",
        plural: "Silky Terriers",
        url: "/animals/",
    },
    {
        id: "toy_fox_terrier",
        type: "dog",
        category: "toy",
        label: "Toy Fox Terrier",
        plural: "Toy Fox Terriers",
        url: "/animals/",
    },
    {
        id: "yorkshire_terrier",
        type: "dog",
        category: "toy",
        label: "Yorkshire Terrier",
        plural: "Yorkshire Terriers",
        url: "/animals/",
    },

    {
        id: "american_eskimo_dog",
        type: "dog",
        category: "non_sporting",
        label: "American Eskimo Dog",
        plural: "American Eskimo Dogs",
        url: "/animals/",
    },
    {
        id: "bichon_frise",
        type: "dog",
        category: "non_sporting",
        label: "Bichon Frise",
        plural: "Bichon Frises",
        url: "/animals/",
    },
    {
        id: "boston_terrier",
        type: "dog",
        category: "non_sporting",
        label: "Boston Terrier",
        plural: "Boston Terriers",
        url: "/animals/",
    },
    { id: "bulldog", type: "dog", category: "non_sporting", label: "Bulldog", plural: "Bulldogs", url: "/animals/" },
    {
        id: "chinese_shar_pei",
        type: "dog",
        category: "non_sporting",
        label: "Chinese Shar-Pei",
        plural: "Chinese Shar-Peis",
        url: "/animals/",
    },
    {
        id: "chow_chow",
        type: "dog",
        category: "non_sporting",
        label: "Chow Chow",
        plural: "Chow Chows",
        url: "/animals/",
    },
    {
        id: "coton_de_tulear",
        type: "dog",
        category: "non_sporting",
        label: "Coton de Tulear",
        plural: "Coton de Tulears",
        url: "/animals/",
    },
    {
        id: "dalmatian",
        type: "dog",
        category: "non_sporting",
        label: "Dalmatian",
        plural: "Dalmatians",
        url: "/animals/",
    },
    {
        id: "finnish_spitz",
        type: "dog",
        category: "non_sporting",
        label: "Finnish Spitz",
        plural: "Finnish Spitzes",
        url: "/animals/",
    },
    {
        id: "french_bulldog",
        type: "dog",
        category: "non_sporting",
        label: "French Bulldog",
        plural: "French Bulldogs",
        url: "/animals/",
    },
    { id: "keeshond", type: "dog", category: "non_sporting", label: "Keeshond", plural: "Keeshonds", url: "/animals/" },
    {
        id: "lhasa_apso",
        type: "dog",
        category: "non_sporting",
        label: "Lhasa Apso",
        plural: "Lhasa Apsos",
        url: "/animals/",
    },
    { id: "lowchen", type: "dog", category: "non_sporting", label: "Lowchen", plural: "Lowchens", url: "/animals/" },
    {
        id: "norwegian_lundehund",
        type: "dog",
        category: "non_sporting",
        label: "Norwegian Lundehund",
        plural: "Norwegian Lundehunds",
        url: "/animals/",
    },
    { id: "poodle", type: "dog", category: "non_sporting", label: "Poodle", plural: "Poodles", url: "/animals/" },
    {
        id: "schipperke",
        type: "dog",
        category: "non_sporting",
        label: "Schipperke",
        plural: "Schipperkes",
        url: "/animals/",
    },
    {
        id: "shiba_inu",
        type: "dog",
        category: "non_sporting",
        label: "Shiba Inu",
        plural: "Shiba Inus",
        url: "/animals/",
    },
    {
        id: "tibetan_spaniel",
        type: "dog",
        category: "non_sporting",
        label: "Tibetan Spaniel",
        plural: "Tibetan Spaniels",
        url: "/animals/",
    },
    {
        id: "tibetan_terrier",
        type: "dog",
        category: "non_sporting",
        label: "Tibetan Terrier",
        plural: "Tibetan Terriers",
        url: "/animals/",
    },
    {
        id: "xoloitzcuintli",
        type: "dog",
        category: "non_sporting",
        label: "Xoloitzcuintli",
        plural: "Xoloitzcuintlis",
        url: "/animals/",
    },

    {
        id: "australian_cattle_dog",
        type: "dog",
        category: "herding",
        label: "Australian Cattle Dog",
        plural: "Australian Cattle Dogs",
        url: "/animals/",
    },
    {
        id: "australian_shepherd",
        type: "dog",
        category: "herding",
        label: "Australian Shepherd",
        plural: "Australian Shepherds",
        url: "/animals/",
    },
    {
        id: "bearded_collie",
        type: "dog",
        category: "herding",
        label: "Bearded Collie",
        plural: "Bearded Collies",
        url: "/animals/",
    },
    { id: "beauceron", type: "dog", category: "herding", label: "Beauceron", plural: "Beaucerons", url: "/animals/" },
    {
        id: "belgian_laekenois",
        type: "dog",
        category: "herding",
        label: "Belgian Laekenois",
        plural: "Belgian Laekenoises",
        url: "/animals/",
    },
    {
        id: "belgian_malinois",
        type: "dog",
        category: "herding",
        label: "Belgian Malinois",
        plural: "Belgian Malinois",
        url: "/animals/",
    },
    {
        id: "belgian_sheepdog",
        type: "dog",
        category: "herding",
        label: "Belgian Sheepdog",
        plural: "Belgian Sheepdogs",
        url: "/animals/",
    },
    {
        id: "belgian_tervuren",
        type: "dog",
        category: "herding",
        label: "Belgian Tervuren",
        plural: "Belgian Tervurens",
        url: "/animals/",
    },
    {
        id: "bergamasco",
        type: "dog",
        category: "herding",
        label: "Bergamasco",
        plural: "Bergamascos",
        url: "/animals/",
    },
    {
        id: "berger_picard",
        type: "dog",
        category: "herding",
        label: "Berger Picard",
        plural: "Berger Picards",
        url: "/animals/",
    },
    {
        id: "border_collie",
        type: "dog",
        category: "herding",
        label: "Border Collie",
        plural: "Border Collies",
        url: "/animals/",
    },
    {
        id: "bouvier_des_flanders",
        type: "dog",
        category: "herding",
        label: "Bouvier Des Flanders",
        plural: "Bouviers Des Flanders",
        url: "/animals/",
    },
    { id: "briard", type: "dog", category: "herding", label: "Briard", plural: "Briards", url: "/animals/" },
    {
        id: "canaan_dog",
        type: "dog",
        category: "herding",
        label: "Canaan Dog",
        plural: "Canaan Dogs",
        url: "/animals/",
    },
    {
        id: "cardigan_welsh_corgi",
        type: "dog",
        category: "herding",
        label: "Cardigan Welsh Corgi",
        plural: "Cardigan Welsh Corgis",
        url: "/animals/",
    },
    { id: "collie", type: "dog", category: "herding", label: "Collie", plural: "Collies", url: "/animals/" },
    {
        id: "entlebucher_mountain_dog",
        type: "dog",
        category: "herding",
        label: "Entlebucher Mountain Dog",
        plural: "Entlebucher Mountain Dogs",
        url: "/animals/",
    },
    {
        id: "finnish_lapphund",
        type: "dog",
        category: "herding",
        label: "Finnish Lapphund",
        plural: "Finnish Lapphunds",
        url: "/animals/",
    },
    {
        id: "german_shepherd",
        type: "dog",
        category: "herding",
        label: "German Shepherd",
        plural: "German Shepherds",
        url: "/animals/",
    },
    {
        id: "icelandic_sheepdog",
        type: "dog",
        category: "herding",
        label: "Icelandic Sheepdog",
        plural: "Icelandic Sheepdogs",
        url: "/animals/",
    },
    {
        id: "lancashire_heeler",
        type: "dog",
        category: "herding",
        label: "Lancashire Heeler",
        plural: "Lancashire Heelers",
        url: "/animals/",
    },
    {
        id: "miniature_american_shepherd",
        type: "dog",
        category: "herding",
        label: "Miniature American Shepherd",
        plural: "Miniature American Shepherds",
        url: "/animals/",
    },
    { id: "mudi", type: "dog", category: "herding", label: "Mudi", plural: "Mudies", url: "/animals/" },
    {
        id: "norwegian_buhund",
        type: "dog",
        category: "herding",
        label: "Norwegian Buhund",
        plural: "Norwegian Buhunds",
        url: "/animals/",
    },
    {
        id: "old_english_sheepdog",
        type: "dog",
        category: "herding",
        label: "Old English Sheepdog",
        plural: "Old English Sheepdogs",
        url: "/animals/",
    },
    {
        id: "pembroke_welsh_corgi",
        type: "dog",
        category: "herding",
        label: "Pembroke Welsh Corgi",
        plural: "Pembroke Welsh Corgis",
        url: "/animals/",
    },
    {
        id: "polish_lowland_sheepdog",
        type: "dog",
        category: "herding",
        label: "Polish Lowland Sheepdog",
        plural: "Polish Lowland Sheepdogs",
        url: "/animals/",
    },
    { id: "puli", type: "dog", category: "herding", label: "Puli", plural: "Pulis", url: "/animals/" },
    { id: "pumi", type: "dog", category: "herding", label: "Pumi", plural: "Pumis", url: "/animals/" },
    {
        id: "pyrenean_shepherd",
        type: "dog",
        category: "herding",
        label: "Pyrenean Shepherd",
        plural: "Pyrenean Shepherds",
        url: "/animals/",
    },
    {
        id: "shetland_sheepdog",
        type: "dog",
        category: "herding",
        label: "Shetland Sheepdog",
        plural: "Shetland Sheepdogs",
        url: "/animals/",
    },
    {
        id: "spanish_water_dog",
        type: "dog",
        category: "herding",
        label: "Spanish Water Dog",
        plural: "Spanish Water Dogs",
        url: "/animals/",
    },
    {
        id: "swedish_vallhund",
        type: "dog",
        category: "herding",
        label: "Swedish Vallhund",
        plural: "Swedish Vallhunds",
        url: "/animals/",
    },

    {
        id: "american_shorthair",
        type: "cat",
        category: "short_hair",
        label: "American Shorthair",
        plural: "American Shorthairs",
        url: "/animals/",
    },
    {
        id: "british_shorthair",
        type: "cat",
        category: "short_hair",
        label: "British Shorthair",
        plural: "British Shorthairs",
        url: "/animals/",
    },
    { id: "burmese", type: "cat", category: "short_hair", label: "Burmese", plural: "Burmese" },
    { id: "russian_blue", type: "cat", category: "short_hair", label: "Russian Blue", plural: "Russian Blues" },
    { id: "siamese", type: "cat", category: "short_hair", label: "Siamese", plural: "Siamese" },
    {
        id: "oriental_shorthair",
        type: "cat",
        category: "short_hair",
        label: "Oriental Shorthair",
        plural: "Oriental Shorthairs",
    },
    { id: "abyssinian", type: "cat", category: "short_hair", label: "Abyssinian", plural: "Abyssinians" },
    { id: "egyptian_mau", type: "cat", category: "short_hair", label: "Egyptian Mau", plural: "Egyptian Maus" },
    { id: "manx", type: "cat", category: "short_hair", label: "Manx", plural: "Manxes" },
    { id: "tonkinese", type: "cat", category: "short_hair", label: "Tonkinese", plural: "Tonkinese" },

    { id: "bengal", type: "cat", category: "medium_hair", label: "Bengal", plural: "Bengals" },
    { id: "scottish_fold", type: "cat", category: "medium_hair", label: "Scottish Fold", plural: "Scottish Folds" },
    {
        id: "norwegian_forest_cat",
        type: "cat",
        category: "medium_hair",
        label: "Norwegian Forest Cat",
        plural: "Norwegian Forest Cats",
    },
    { id: "ragdoll", type: "cat", category: "medium_hair", label: "Ragdoll", plural: "Ragdolls" },
    { id: "somali", type: "cat", category: "medium_hair", label: "Somali", plural: "Somalis" },
    { id: "turkish_van", type: "cat", category: "medium_hair", label: "Turkish Van", plural: "Turkish Vans" },
    {
        id: "japanese_bobtail",
        type: "cat",
        category: "medium_hair",
        label: "Japanese Bobtail",
        plural: "Japanese Bobtails",
    },
    { id: "ocicat", type: "cat", category: "medium_hair", label: "Ocicat", plural: "Ocicats" },
    { id: "balinese", type: "cat", category: "medium_hair", label: "Balinese", plural: "Balinese" },
    { id: "havana_brown", type: "cat", category: "medium_hair", label: "Havana Brown", plural: "Havana Browns" },

    { id: "persian", type: "cat", category: "long_hair", label: "Persian", plural: "Persians" },
    { id: "maine_coon", type: "cat", category: "long_hair", label: "Maine Coon", plural: "Maine Coons" },
    { id: "himalayan", type: "cat", category: "long_hair", label: "Himalayan", plural: "Himalayans" },
    { id: "birman", type: "cat", category: "long_hair", label: "Birman", plural: "Birmans" },
    { id: "siberian", type: "cat", category: "long_hair", label: "Siberian", plural: "Siberians" },
    { id: "ragamuffin", type: "cat", category: "long_hair", label: "Ragamuffin", plural: "Ragamuffins" },
    { id: "turkish_angora", type: "cat", category: "long_hair", label: "Turkish Angora", plural: "Turkish Angoras" },
    {
        id: "chantilly_tiffany",
        type: "cat",
        category: "long_hair",
        label: "Chantilly-Tiffany",
        plural: "Chantilly-Tiffanys",
    },
    {
        id: "somali_longhair",
        type: "cat",
        category: "long_hair",
        label: "Somali Longhair",
        plural: "Somali Longhairs",
    },
    {
        id: "scottish_longhair",
        type: "cat",
        category: "long_hair",
        label: "Scottish Longhair",
        plural: "Scottish Longhairs",
    },

    { id: "sphynx", type: "cat", category: "hairless", label: "Sphynx", plural: "Sphynxes" },
    { id: "peterbald", type: "cat", category: "hairless", label: "Peterbald", plural: "Peterbalds" },
    { id: "donskoy", type: "cat", category: "hairless", label: "Donskoy", plural: "Donskoys" },
    { id: "bambino", type: "cat", category: "hairless", label: "Bambino", plural: "Bambinos" },
    {
        id: "ukrainian_levkoy",
        type: "cat",
        category: "hairless",
        label: "Ukrainian Levkoy",
        plural: "Ukrainian Levkoys",
    },

    {
        id: "american_quarter_horse",
        type: "horse",
        category: "riding",
        label: "American Quarter Horse",
        plural: "American Quarter Horses",
    },
    { id: "thoroughbred", type: "horse", category: "riding", label: "Thoroughbred", plural: "Thoroughbreds" },
    { id: "arabian", type: "horse", category: "riding", label: "Arabian", plural: "Arabians" },
    { id: "appaloosa", type: "horse", category: "riding", label: "Appaloosa", plural: "Appaloosas" },
    { id: "morgan", type: "horse", category: "riding", label: "Morgan", plural: "Morgans" },
    { id: "hanoverian", type: "horse", category: "riding", label: "Hanoverian", plural: "Hanoverians" },
    { id: "trakehner", type: "horse", category: "riding", label: "Trakehner", plural: "Trakehners" },
    { id: "andalusian", type: "horse", category: "riding", label: "Andalusian", plural: "Andalusians" },
    { id: "lusitano", type: "horse", category: "riding", label: "Lusitano", plural: "Lusitanos" },
    { id: "warmblood", type: "horse", category: "riding", label: "Warmblood", plural: "Warmbloods" },

    { id: "clydesdale", type: "horse", category: "working_horse", label: "Clydesdale", plural: "Clydesdales" },
    { id: "percheron", type: "horse", category: "working_horse", label: "Percheron", plural: "Percherons" },
    { id: "belgian", type: "horse", category: "working_horse", label: "Belgian", plural: "Belgians" },
    { id: "shire", type: "horse", category: "working_horse", label: "Shire", plural: "Shires" },
    {
        id: "american_cream_draft",
        type: "horse",
        category: "working_horse",
        label: "American Cream Draft",
        plural: "American Cream Drafts",
    },
    {
        id: "suffolk_punch",
        type: "horse",
        category: "working_horse",
        label: "Suffolk Punch",
        plural: "Suffolk Punches",
    },
    { id: "freiberger", type: "horse", category: "working_horse", label: "Freiberger", plural: "Freibergers" },
    { id: "hackney", type: "horse", category: "working_horse", label: "Hackney", plural: "Hackneys" },
    {
        id: "american_standardbred",
        type: "horse",
        category: "working_horse",
        label: "American Standardbred",
        plural: "American Standardbreds",
    },
    {
        id: "irish_draught",
        type: "horse",
        category: "working_horse",
        label: "Irish Draught",
        plural: "Irish Draughts",
    },

    { id: "shetland_pony", type: "horse", category: "pony", label: "Shetland Pony", plural: "Shetland Ponies" },
    { id: "welsh_pony", type: "horse", category: "pony", label: "Welsh Pony", plural: "Welsh Ponies" },
    { id: "connemara_pony", type: "horse", category: "pony", label: "Connemara Pony", plural: "Connemara Ponies" },
    { id: "fjord_pony", type: "horse", category: "pony", label: "Fjord Pony", plural: "Fjord Ponies" },
    { id: "dartmoor_pony", type: "horse", category: "pony", label: "Dartmoor Pony", plural: "Dartmoor Ponies" },
    { id: "haflinger", type: "horse", category: "pony", label: "Haflinger", plural: "Haflingers" },
    { id: "new_forest_pony", type: "horse", category: "pony", label: "New Forest Pony", plural: "New Forest Ponies" },
    { id: "exmoor_pony", type: "horse", category: "pony", label: "Exmoor Pony", plural: "Exmoor Ponies" },
    {
        id: "chincoteague_pony",
        type: "horse",
        category: "pony",
        label: "Chincoteague Pony",
        plural: "Chincoteague Ponies",
    },
    {
        id: "pony_of_the_americas",
        type: "horse",
        category: "pony",
        label: "Pony of the Americas",
        plural: "Ponies of the Americas",
    },

    {
        id: "miniature_horse",
        type: "horse",
        category: "miniature",
        label: "Miniature Horse",
        plural: "Miniature Horses",
    },
    {
        id: "american_miniature_horse",
        type: "horse",
        category: "miniature",
        label: "American Miniature Horse",
        plural: "American Miniature Horses",
    },
    { id: "falabella", type: "horse", category: "miniature", label: "Falabella", plural: "Falabellas" },
    {
        id: "miniature_shetland",
        type: "horse",
        category: "miniature",
        label: "Miniature Shetland",
        plural: "Miniature Shetlands",
    },
    {
        id: "miniature_appaloosa",
        type: "horse",
        category: "miniature",
        label: "Miniature Appaloosa",
        plural: "Miniature Appaloosas",
    },

    { id: "holstein", type: "livestock", category: "cattle", label: "Holstein", plural: "Holsteins" },
    { id: "angus", type: "livestock", category: "cattle", label: "Angus", plural: "Angus" },
    { id: "hereford", type: "livestock", category: "cattle", label: "Hereford", plural: "Herefords" },
    { id: "jersey", type: "livestock", category: "cattle", label: "Jersey", plural: "Jerseys" },
    { id: "simmental", type: "livestock", category: "cattle", label: "Simmental", plural: "Simmentals" },

    { id: "merino", type: "livestock", category: "sheep", label: "Merino", plural: "Merinos" },
    { id: "suffolk", type: "livestock", category: "sheep", label: "Suffolk", plural: "Suffolks" },
    { id: "dorset", type: "livestock", category: "sheep", label: "Dorset", plural: "Dorsets" },
    { id: "hampshire", type: "livestock", category: "sheep", label: "Hampshire", plural: "Hampshires" },
    { id: "romney", type: "livestock", category: "sheep", label: "Romney", plural: "Romneys" },

    { id: "yorkshire", type: "livestock", category: "pig", label: "Yorkshire", plural: "Yorkshires" },
    { id: "berkshire", type: "livestock", category: "pig", label: "Berkshire", plural: "Berkshires" },
    { id: "duroc", type: "livestock", category: "pig", label: "Duroc", plural: "Durocs" },
    { id: "hampshire", type: "livestock", category: "pig", label: "Hampshire", plural: "Hampshires" },
    { id: "landrace", type: "livestock", category: "pig", label: "Landrace", plural: "Landraces" },

    { id: "nubian", type: "livestock", category: "goat", label: "Nubian", plural: "Nubians" },
    { id: "boer", type: "livestock", category: "goat", label: "Boer", plural: "Boers" },
    { id: "saanen", type: "livestock", category: "goat", label: "Saanen", plural: "Saanens" },
    { id: "alpine", type: "livestock", category: "goat", label: "Alpine", plural: "Alpines" },
    { id: "toggenburg", type: "livestock", category: "goat", label: "Toggenburg", plural: "Toggenburgs" },

    {
        id: "classic_llama",
        type: "livestock",
        category: "llama_alpaca",
        label: "Classic Llama",
        plural: "Classic Llamas",
    },
    { id: "suri_llama", type: "livestock", category: "llama_alpaca", label: "Suri Llama", plural: "Suri Llamas" },
    {
        id: "huacaya_llama",
        type: "livestock",
        category: "llama_alpaca",
        label: "Huacaya Llama",
        plural: "Huacaya Llamas",
    },
    {
        id: "huacaya_alpaca",
        type: "livestock",
        category: "llama_alpaca",
        label: "Huacaya Alpaca",
        plural: "Huacaya Alpacas",
    },
    { id: "suri_alpaca", type: "livestock", category: "llama_alpaca", label: "Suri Alpaca", plural: "Suri Alpacas" },

    {
        id: "rhode_island_red",
        type: "livestock",
        category: "poultry",
        label: "Rhode Island Red",
        plural: "Rhode Island Reds",
    },
    { id: "leghorn", type: "livestock", category: "poultry", label: "Leghorn", plural: "Leghorns" },
    { id: "plymouth_rock", type: "livestock", category: "poultry", label: "Plymouth Rock", plural: "Plymouth Rocks" },
    { id: "sussex", type: "livestock", category: "poultry", label: "Sussex", plural: "Sussex" },
    { id: "orpington", type: "livestock", category: "poultry", label: "Orpington", plural: "Orpingtons" },

    { id: "budgie", type: "small_pet", category: "bird", label: "Budgie", plural: "Budgies" },
    { id: "cockatiel", type: "small_pet", category: "bird", label: "Cockatiel", plural: "Cockatiels" },
    { id: "lovebird", type: "small_pet", category: "bird", label: "Lovebird", plural: "Lovebirds" },
    { id: "parakeet", type: "small_pet", category: "bird", label: "Parakeet", plural: "Parakeets" },
    { id: "canary", type: "small_pet", category: "bird", label: "Canary", plural: "Canaries" },
    { id: "finch", type: "small_pet", category: "bird", label: "Finch", plural: "Finches" },
    {
        id: "african_grey_parrot",
        type: "small_pet",
        category: "bird",
        label: "African Grey Parrot",
        plural: "African Grey Parrots",
    },
    { id: "cockatoo", type: "small_pet", category: "bird", label: "Cockatoo", plural: "Cockatoos" },
    { id: "macaw", type: "small_pet", category: "bird", label: "Macaw", plural: "Macaws" },

    {
        id: "syrian_hamster",
        type: "small_pet",
        category: "hamster",
        label: "Syrian Hamster",
        plural: "Syrian Hamsters",
    },
    {
        id: "roborovski_hamster",
        type: "small_pet",
        category: "hamster",
        label: "Roborovski Hamster",
        plural: "Roborovski Hamsters",
    },
    {
        id: "chinese_hamster",
        type: "small_pet",
        category: "hamster",
        label: "Chinese Hamster",
        plural: "Chinese Hamsters",
    },

    { id: "holland_lop", type: "small_pet", category: "bunny", label: "Holland Lop", plural: "Holland Lops" },
    {
        id: "netherland_dwarf",
        type: "small_pet",
        category: "bunny",
        label: "Netherland Dwarf",
        plural: "Netherland Dwarfs",
    },
    { id: "lionhead", type: "small_pet", category: "bunny", label: "Lionhead", plural: "Lionheads" },
    { id: "mini_rex", type: "small_pet", category: "bunny", label: "Mini Rex", plural: "Mini Rexes" },
    { id: "flemish_giant", type: "small_pet", category: "bunny", label: "Flemish Giant", plural: "Flemish Giants" },

    { id: "american", type: "small_pet", category: "guinea_pig", label: "American", plural: "Americans" },
    { id: "abyssinian", type: "small_pet", category: "guinea_pig", label: "Abyssinian", plural: "Abyssinians" },
    { id: "peruvian", type: "small_pet", category: "guinea_pig", label: "Peruvian", plural: "Peruvians" },
    { id: "sheltie", type: "small_pet", category: "guinea_pig", label: "Sheltie", plural: "Shelties" },
    { id: "teddy", type: "small_pet", category: "guinea_pig", label: "Teddy", plural: "Teddies" },

    { id: "fancy_mouse", type: "small_pet", category: "mouse", label: "Fancy Mouse", plural: "Fancy Mice" },
    { id: "burmese_mouse", type: "small_pet", category: "mouse", label: "Burmese Mouse", plural: "Burmese Mice" },
    { id: "satin_mouse", type: "small_pet", category: "mouse", label: "Satin Mouse", plural: "Satin Mice" },

    { id: "standard_rat", type: "small_pet", category: "rat", label: "Standard Rat", plural: "Standard Rats" },
    { id: "dumbo_rat", type: "small_pet", category: "rat", label: "Dumbo Rat", plural: "Dumbo Rats" },
    { id: "hairless_rat", type: "small_pet", category: "rat", label: "Hairless Rat", plural: "Hairless Rats" },

    {
        id: "standard_ferret",
        type: "small_pet",
        category: "ferret",
        label: "Standard Ferret",
        plural: "Standard Ferrets",
    },
    { id: "albino_ferret", type: "small_pet", category: "ferret", label: "Albino Ferret", plural: "Albino Ferrets" },
    { id: "sable_ferret", type: "small_pet", category: "ferret", label: "Sable Ferret", plural: "Sable Ferrets" },
    { id: "silver_ferret", type: "small_pet", category: "ferret", label: "Silver Ferret", plural: "Silver Ferrets" },

    { id: "breed_wildlife", type: "other", category: "wildlife", label: "Wildlife", plural: "Wildlife" },
    { id: "breed_exotic", type: "other", category: "exotic", label: "Exotic", plural: "Exotics" },
];
