// Animal Breeds Module
export const breeds = {
    dog: {
        sporting: [
            {
                key: "american_water_spaniel",
                label: "American Water Spaniel",
            },
            { key: "barbet", label: "Barbet" },
            { key: "boykin_spaniel", label: "Boykin Spaniel" },
            { key: "bracco_italiano", label: "Bracco Italiano" },
            { key: "brittany", label: "Brittany" },
            {
                key: "chesapeake_bay_retriever",
                label: "Chesapeake Bay Retriever",
            },
            { key: "clumber_spaniel", label: "Clumber Spaniel" },
            { key: "cocker_spaniel", label: "Cocker Spaniel" },
            {
                key: "curly_coated_retriever",
                label: "Curly-Coated Retriever",
            },
            {
                key: "english_cocker_spaniel",
                label: "English Cocker Spaniel",
            },
            { key: "english_setter", label: "English Setter" },
            {
                key: "english_springer_spaniel",
                label: "English Springer Spaniel",
            },
            { key: "field_spaniel", label: "Field Spaniel" },
            {
                key: "flat_coated_retriever",
                label: "Flat-Coated Retriever",
            },
            {
                key: "german_shorthaired_pointer",
                label: "German Shorthaired Pointer",
            },
            {
                key: "german_wirehaired_pointer",
                label: "German Wirehaired Pointer",
            },
            { key: "golden_retriever", label: "Golden Retriever" },
            { key: "gordon_setter", label: "Gordon Setter" },
            {
                key: "irish_red_and_white_setter",
                label: "Irish Red and White Setter",
            },
            { key: "irish_setter", label: "Irish Setter" },
            { key: "irish_water_spaniel", label: "Irish Water Spaniel" },
            { key: "labrador_retriever", label: "Labrador Retriever" },
            { key: "lagotto_romagnolo", label: "Lagotto Romagnolo" },
            {
                key: "nederlandse_kooikerhondje",
                label: "Nederlandse Kooikerhondje",
            },
            {
                key: "nova_scotia_duck_tolling_retriever",
                label: "Nova Scotia Duck Tolling Retriever",
            },
            { key: "pointer", label: "Pointer" },
            { key: "spinone_italiano", label: "Spinone Italiano" },
            { key: "sussex_spaniel", label: "Sussex Spaniel" },
            { key: "vizsla", label: "Vizsla" },
            { key: "weimaraner", label: "Weimaraner" },
            {
                key: "welsh_springer_spaniel",
                label: "Welsh Springer Spaniel",
            },
            {
                key: "wirehaired_pointing_griffon",
                label: "Wirehaired Pointing Griffon",
            },
            { key: "wirehaired_vizsla", label: "Wirehaired Vizsla" },
            { key: "other", label: "Other" },
        ],
        hound: [
            { key: "afghan_hound", label: "Afghan Hound" },
            {
                key: "american_english_coonhound",
                label: "American English Coonhound",
            },
            { key: "american_foxhound", label: "American Foxhound" },
            { key: "azawakh", label: "Azawakh" },
            { key: "basenji", label: "Basenji" },
            { key: "basset_hound", label: "Basset Hound" },
            { key: "beagle", label: "Beagle" },
            {
                key: "black_and_tan_coonhound",
                label: "Black and Tan Coonhound",
            },
            { key: "bloodhound", label: "Bloodhound" },
            { key: "bluetick_coonhound", label: "Bluetick Coonhound" },
            { key: "borzoi", label: "Borzoi" },
            { key: "cirneco_dell_etna", label: "Cirneco dell’Etna" },
            { key: "dachshund", label: "Dachshund" },
            { key: "english_foxhound", label: "English Foxhound" },
            {
                key: "grand_basset_griffon_vendeen",
                label: "Grand Basset Griffon Vendeen",
            },
            { key: "greyhound", label: "Greyhound" },
            { key: "harrier", label: "Harrier" },
            { key: "ibizan_hound", label: "Ibizan Hound" },
            { key: "irish_wolfhound", label: "Irish Wolfhound" },
            { key: "norwegian_elkhound", label: "Norwegian Elkhound" },
            { key: "otterhound", label: "Otterhound" },
            {
                key: "petit_basset_griffon_vendeen",
                label: "Petit Basset Griffon Vendeen",
            },
            { key: "pharaoh_hound", label: "Pharaoh Hound" },
            { key: "plott_hound", label: "Plott Hound" },
            {
                key: "portuguese_podengo_pequeno",
                label: "Portuguese Podengo Pequeno",
            },
            { key: "redbone_coonhound", label: "Redbone Coonhound" },
            { key: "rhodesian_ridgeback", label: "Rhodesian Ridgeback" },
            { key: "saluki", label: "Saluki" },
            { key: "scottish_deerhound", label: "Scottish Deerhound" },
            { key: "sloughi", label: "Sloughi" },
            {
                key: "treeing_walker_coonhound",
                label: "Treeing Walker Coonhound",
            },
            { key: "whippet", label: "Whippet" },
            { key: "other", label: "Other" },
        ],

        working: [
            { key: "akita", label: "Akita" },
            { key: "alaskan_malamute", label: "Alaskan Malamute" },
            { key: "anatolian_shepherd_dog", label: "Anatolian Shepherd Dog" },
            { key: "bernese_mountain_dog", label: "Bernese Mountain Dog" },
            { key: "black_russian_terrier", label: "Black Russian Terrier" },
            { key: "boerboel", label: "Boerboel" },
            { key: "boxer", label: "Boxer" },
            { key: "bullmastiff", label: "Bullmastiff" },
            { key: "cane_corso", label: "Cane Corso" },
            { key: "chinook", label: "Chinook" },
            { key: "danish_swedish_farmdog", label: "Danish-Swedish Farmdog" },
            { key: "doberman_pinscher", label: "Doberman Pinscher" },
            { key: "dogo_argentino", label: "Dogo Argentino" },
            { key: "dogue_de_bordeaux", label: "Dogue de Bordeaux" },
            { key: "german_pinscher", label: "German Pinscher" },
            { key: "giant_schnauzer", label: "Giant Schnauzer" },
            { key: "great_dane", label: "Great Dane" },
            { key: "great_pyrenees", label: "Great Pyrenees" },
            {
                key: "greater_swiss_mountain_dog",
                label: "Greater Swiss Mountain Dog",
            },
            { key: "komondor", label: "Komondor" },
            { key: "kuvasz", label: "Kuvasz" },
            { key: "leonberger", label: "Leonberger" },
            { key: "mastiff", label: "Mastiff" },
            { key: "neapolitan_mastiff", label: "Neapolitan Mastiff" },
            { key: "newfoundland", label: "Newfoundland" },
            { key: "portuguese_water_dog", label: "Portuguese Water Dog" },
            { key: "rottweiler", label: "Rottweiler" },
            { key: "st_bernard", label: "St. Bernard" },
            { key: "samoyed", label: "Samoyed" },
            { key: "siberian_husky", label: "Siberian Husky" },
            { key: "standard_schnauzer", label: "Standard Schnauzer" },
            { key: "tibetan_mastiff", label: "Tibetan Mastiff" },
            { key: "other", label: "Other" },
        ],

        terrier: [
            { key: "airedale_terrier", label: "Airedale Terrier" },
            {
                key: "american_hairless_terrier",
                label: "American Hairless Terrier",
            },
            {
                key: "american_staffordshire_terrier",
                label: "American Staffordshire Terrier",
            },
            { key: "australian_terrier", label: "Australian Terrier" },
            { key: "bedlington_terrier", label: "Bedlington Terrier" },
            { key: "border_terrier", label: "Border Terrier" },
            { key: "bull_terrier", label: "Bull Terrier" },
            { key: "cairn_terrier", label: "Cairn Terrier" },
            { key: "cesky_terrier", label: "Cesky Terrier" },
            { key: "dandie_dinmont_terrier", label: "Dandie Dinmont Terrier" },
            { key: "glen_of_imaal_terrier", label: "Glen of Imaal Terrier" },
            { key: "irish_terrier", label: "Irish Terrier" },
            { key: "kerry_blue_terrier", label: "Kerry Blue Terrier" },
            { key: "lakeland_terrier", label: "Lakeland Terrier" },
            { key: "manchester_terrier", label: "Manchester Terrier" },
            { key: "miniature_bull_terrier", label: "Miniature Bull Terrier" },
            { key: "miniature_schnauzer", label: "Miniature Schnauzer" },
            { key: "norfolk_terrier", label: "Norfolk Terrier" },
            { key: "norwich_terrier", label: "Norwich Terrier" },
            { key: "parson_russell_terrier", label: "Parson Russell Terrier" },
            { key: "rat_terrier", label: "Rat Terrier" },
            { key: "russell_terrier", label: "Russell Terrier" },
            { key: "scottish_terrier", label: "Scottish Terrier" },
            { key: "sealyham_terrier", label: "Sealyham Terrier" },
            { key: "skye_terrier", label: "Skye Terrier" },
            { key: "smooth_fox_terrier", label: "Smooth Fox Terrier" },
            {
                key: "soft_coated_wheaton_terrier",
                label: "Soft Coated Wheaton Terrier",
            },
            {
                key: "staffordshire_bull_terrier",
                label: "Staffordshire Bull Terrier",
            },
            { key: "welsh_terrier", label: "Welsh Terrier" },
            {
                key: "west_highland_white_terrier",
                label: "West Highland White Terrier",
            },
            { key: "wire_fox_terrier", label: "Wire Fox Terrier" },
            { key: "other", label: "Other" },
        ],

        toy: [
            { key: "affenpinscher", label: "Affenpinscher" },
            { key: "biewer_terrier", label: "Biewer Terrier" },
            { key: "brussels_griffon", label: "Brussels Griffon" },
            {
                key: "cavalier_king_charles_spaniel",
                label: "Cavalier King Charles Spaniel",
            },
            { key: "chihuahua", label: "Chihuahua" },
            { key: "chinese_crested", label: "Chinese Crested" },
            { key: "english_toy_spaniel", label: "English Toy Spaniel" },
            { key: "havanese", label: "Havanese" },
            { key: "italian_greyhound", label: "Italian Greyhound" },
            { key: "japanese_chin", label: "Japanese Chin" },
            { key: "maltese", label: "Maltese" },
            { key: "manchester_terrier", label: "Manchester Terrier" },
            { key: "miniature_pinscher", label: "Miniature Pinscher" },
            { key: "papillon", label: "Papillon" },
            { key: "pekingese", label: "Pekingese" },
            { key: "pomeranian", label: "Pomeranian" },
            { key: "poodle", label: "Poodle" },
            { key: "pug", label: "Pug" },
            { key: "russian_toy", label: "Russian Toy" },
            { key: "shih_tzu", label: "Shih Tzu" },
            { key: "silky_terrier", label: "Silky Terrier" },
            { key: "toy_fox_terrier", label: "Toy Fox Terrier" },
            { key: "yorkshire_terrier", label: "Yorkshire Terrier" },
            { key: "other", label: "Other" },
        ],

        non_sporting: [
            { key: "american_eskimo_dog", label: "American Eskimo Dog" },
            { key: "bichon_frise", label: "Bichon Frise" },
            { key: "boston_terrier", label: "Boston Terrier" },
            { key: "bulldog", label: "Bulldog" },
            { key: "chinese_shar_pei", label: "Chinese Shar-Pei" },
            { key: "chow_chow", label: "Chow Chow" },
            { key: "coton_de_tulear", label: "Coton de Tulear" },
            { key: "dalmatian", label: "Dalmatian" },
            { key: "finnish_spitz", label: "Finnish Spitz" },
            { key: "french_bulldog", label: "French Bulldog" },
            { key: "keeshond", label: "Keeshond" },
            { key: "lhasa_apso", label: "Lhasa Apso" },
            { key: "lowchen", label: "Lowchen" },
            { key: "norwegian_lundehund", label: "Norwegian Lundehund" },
            { key: "poodle", label: "Poodle" },
            { key: "schipperke", label: "Schipperke" },
            { key: "shiba_inu", label: "Shiba Inu" },
            { key: "tibetan_spaniel", label: "Tibetan Spaniel" },
            { key: "tibetan_terrier", label: "Tibetan Terrier" },
            { key: "xoloitzcuintli", label: "Xoloitzcuintli" },
            { key: "other", label: "Other" },
        ],

        herding: [
            { key: "australian_cattle_dog", label: "Australian Cattle Dog" },
            { key: "australian_shepherd", label: "Australian Shepherd" },
            { key: "bearded_collie", label: "Bearded Collie" },
            { key: "beauceron", label: "Beauceron" },
            { key: "belgian_laekenois", label: "Belgian Laekenois" },
            { key: "belgian_malinois", label: "Belgian Malinois" },
            { key: "belgian_sheepdog", label: "Belgian Sheepdog" },
            { key: "belgian_tervuren", label: "Belgian Tervuren" },
            { key: "bergamasco", label: "Bergamasco" },
            { key: "berger_picard", label: "Berger Picard" },
            { key: "border_collie", label: "Border Collie" },
            { key: "bouvier_des_flanders", label: "Bouvier Des Flanders" },
            { key: "briard", label: "Briard" },
            { key: "canaan_dog", label: "Canaan Dog" },
            { key: "cardigan_welsh_corgi", label: "Cardigan Welsh Corgi" },
            { key: "collie", label: "Collie" },
            {
                key: "entlebucher_mountain_dog",
                label: "Entlebucher Mountain Dog",
            },
            { key: "finnish_lapphund", label: "Finnish Lapphund" },
            { key: "german_shepherd", label: "German Shepherd" },
            { key: "icelandic_sheepdog", label: "Icelandic Sheepdog" },
            { key: "lancashire_heeler", label: "Lancashire Heeler" },
            {
                key: "miniature_american_shepherd",
                label: "Miniature American Shepherd",
            },
            { key: "mudi", label: "Mudi" },
            { key: "norwegian_buhund", label: "Norwegian Buhund" },
            { key: "old_english_sheepdog", label: "Old English Sheepdog" },
            { key: "pembroke_welsh_corgi", label: "Pembroke Welsh Corgi" },
            {
                key: "polish_lowland_sheepdog",
                label: "Polish Lowland Sheepdog",
            },
            { key: "puli", label: "Puli" },
            { key: "pumi", label: "Pumi" },
            { key: "pyrenean_shepherd", label: "Pyrenean Shepherd" },
            { key: "shetland_sheepdog", label: "Shetland Sheepdog" },
            { key: "spanish_water_dog", label: "Spanish Water Dog" },
            { key: "swedish_vallhund", label: "Swedish Vallhund" },
            { key: "other", label: "Other" },
        ],
        mixed: [{ key: "mixed", label: "Mixed" }],
        other: [{ key: "other", label: "Other" }],
    },

    cat: {
        short_hair: [
            { key: "american_shorthair", label: "American Shorthair" },
            { key: "british_shorthair", label: "British Shorthair" },
            { key: "burmese", label: "Burmese" },
            { key: "russian_blue", label: "Russian Blue" },
            { key: "siamese", label: "Siamese" },
            { key: "oriental_shorthair", label: "Oriental Shorthair" },
            { key: "abyssinian", label: "Abyssinian" },
            { key: "egyptian_mau", label: "Egyptian Mau" },
            { key: "manx", label: "Manx" },
            { key: "tonkinese", label: "Tonkinese" },
            { key: "other", label: "Other" },
        ],
        medium_hair: [
            { key: "bengal", label: "Bengal" },
            { key: "scottish_fold", label: "Scottish Fold" },
            { key: "norwegian_forest_cat", label: "Norwegian Forest Cat" },
            { key: "ragdoll", label: "Ragdoll" },
            { key: "somali", label: "Somali" },
            { key: "turkish_van", label: "Turkish Van" },
            { key: "japanese_bobtail", label: "Japanese Bobtail" },
            { key: "ocicat", label: "Ocicat" },
            { key: "balinese", label: "Balinese" },
            { key: "havana_brown", label: "Havana Brown" },
            { key: "other", label: "Other" },
        ],
        long_hair: [
            { key: "persian", label: "Persian" },
            { key: "maine_coon", label: "Maine Coon" },
            { key: "himalayan", label: "Himalayan" },
            { key: "birman", label: "Birman" },
            { key: "siberian", label: "Siberian" },
            { key: "ragamuffin", label: "Ragamuffin" },
            { key: "turkish_angora", label: "Turkish Angora" },
            { key: "chantilly_tiffany", label: "Chantilly-Tiffany" },
            { key: "somali_longhair", label: "Somali Longhair" },
            { key: "scottish_longhair", label: "Scottish Longhair" },
            { key: "other", label: "Other" },
        ],
        hairless: [
            { key: "sphynx", label: "Sphynx" },
            { key: "peterbald", label: "Peterbald" },
            { key: "donskoy", label: "Donskoy" },
            { key: "bambino", label: "Bambino" },
            { key: "ukrainian_levkoy", label: "Ukrainian Levkoy" },
            { key: "other", label: "Other" },
        ],
        other: [{ key: "other", label: "Other" }],
    },
    horse: {
        riding: [
            { key: "american_quarter_horse", label: "American Quarter Horse" },
            { key: "thoroughbred", label: "Thoroughbred" },
            { key: "arabian", label: "Arabian" },
            { key: "appaloosa", label: "Appaloosa" },
            { key: "morgan", label: "Morgan" },
            { key: "hanoverian", label: "Hanoverian" },
            { key: "trakehner", label: "Trakehner" },
            { key: "andalusian", label: "Andalusian" },
            { key: "lusitano", label: "Lusitano" },
            { key: "warmblood", label: "Warmblood" },
            { key: "other", label: "Other" },
        ],
        working: [
            { key: "clydesdale", label: "Clydesdale" },
            { key: "percheron", label: "Percheron" },
            { key: "belgian", label: "Belgian" },
            { key: "shire", label: "Shire" },
            { key: "american_cream_draft", label: "American Cream Draft" },
            { key: "suffolk_punch", label: "Suffolk Punch" },
            { key: "freiberger", label: "Freiberger" },
            { key: "hackney", label: "Hackney" },
            { key: "american_standardbred", label: "American Standardbred" },
            { key: "irish_draught", label: "Irish Draught" },
            { key: "other", label: "Other" },
        ],
        pony: [
            { key: "shetland_pony", label: "Shetland Pony" },
            { key: "welsh_pony", label: "Welsh Pony" },
            { key: "connemara_pony", label: "Connemara Pony" },
            { key: "fjord_pony", label: "Fjord Pony" },
            { key: "dartmoor_pony", label: "Dartmoor Pony" },
            { key: "haflinger", label: "Haflinger" },
            { key: "new_forest_pony", label: "New Forest Pony" },
            { key: "exmoor_pony", label: "Exmoor Pony" },
            { key: "chincoteague_pony", label: "Chincoteague Pony" },
            { key: "pony_of_the_americas", label: "Pony of the Americas" },
            { key: "other", label: "Other" },
        ],
        miniature: [
            { key: "miniature_horse", label: "Miniature Horse" },
            {
                key: "american_miniature_horse",
                label: "American Miniature Horse",
            },
            { key: "falabella", label: "Falabella" },
            { key: "miniature_shetland", label: "Miniature Shetland" },
            { key: "miniature_appaloosa", label: "Miniature Appaloosa" },
            { key: "other", label: "Other" },
        ],
        other: [{ key: "other", label: "Other" }],
    },

    livestock: {
        cattle: [
            { key: "holstein", label: "Holstein" },
            { key: "angus", label: "Angus" },
            { key: "hereford", label: "Hereford" },
            { key: "jersey", label: "Jersey" },
            { key: "simmental", label: "Simmental" },
            { key: "other", label: "Other" },
        ],
        sheep: [
            { key: "merino", label: "Merino" },
            { key: "suffolk", label: "Suffolk" },
            { key: "dorset", label: "Dorset" },
            { key: "hampshire", label: "Hampshire" },
            { key: "romney", label: "Romney" },
            { key: "other", label: "Other" },
        ],
        pig: [
            { key: "yorkshire", label: "Yorkshire" },
            { key: "berkshire", label: "Berkshire" },
            { key: "duroc", label: "Duroc" },
            { key: "hampshire", label: "Hampshire" },
            { key: "landrace", label: "Landrace" },
            { key: "other", label: "Other" },
        ],
        goat: [
            { key: "nubian", label: "Nubian" },
            { key: "boer", label: "Boer" },
            { key: "saanen", label: "Saanen" },
            { key: "alpine", label: "Alpine" },
            { key: "toggenburg", label: "Toggenburg" },
            { key: "other", label: "Other" },
        ],
        llama_alpaca: [
            { key: "classic_llama", label: "Classic Llama" },
            { key: "suri_llama", label: "Suri Llama" },
            { key: "huacaya_llama", label: "Huacaya Llama" },
            { key: "huacaya_alpaca", label: "Huacaya Alpaca" },
            { key: "suri_alpaca", label: "Suri Alpaca" },
            { key: "other", label: "Other" },
        ],
        poultry: [
            { key: "rhode_island_red", label: "Rhode Island Red" },
            { key: "leghorn", label: "Leghorn" },
            { key: "plymouth_rock", label: "Plymouth Rock" },
            { key: "sussex", label: "Sussex" },
            { key: "orpington", label: "Orpington" },
            { key: "other", label: "Other" },
        ],
        other: [{ key: "other", label: "Other" }],
    },

    small_pet: {
        bird: [
            { key: "budgie", label: "Budgie" },
            { key: "cockatiel", label: "Cockatiel" },
            { key: "lovebird", label: "Lovebird" },
            { key: "parakeet", label: "Parakeet" },
            { key: "canary", label: "Canary" },
            { key: "finch", label: "Finch" },
            { key: "african_grey_parrot", label: "African Grey Parrot" },
            { key: "cockatoo", label: "Cockatoo" },
            { key: "macaw", label: "Macaw" },
            { key: "other", label: "Other" },
        ],
        hamster: [
            { key: "syrian_hamster", label: "Syrian Hamster" },
            { key: "roborovski_hamster", label: "Roborovski Hamster" },
            { key: "chinese_hamster", label: "Chinese Hamster" },
            { key: "other", label: "Other" },
        ],
        bunny: [
            { key: "holland_lop", label: "Holland Lop" },
            { key: "netherland_dwarf", label: "Netherland Dwarf" },
            { key: "lionhead", label: "Lionhead" },
            { key: "mini_rex", label: "Mini Rex" },
            { key: "flemish_giant", label: "Flemish Giant" },
            { key: "other", label: "Other" },
        ],
        guinea_pig: [
            { key: "american", label: "American" },
            { key: "abyssinian", label: "Abyssinian" },
            { key: "peruvian", label: "Peruvian" },
            { key: "sheltie", label: "Sheltie" },
            { key: "teddy", label: "Teddy" },
            { key: "other", label: "Other" },
        ],
        mouse: [
            { key: "fancy_mouse", label: "Fancy Mouse" },
            { key: "burmese_mouse", label: "Burmese Mouse" },
            { key: "satin_mouse", label: "Satin Mouse" },
            { key: "other", label: "Other" },
        ],
        rat: [
            { key: "standard_rat", label: "Standard Rat" },
            { key: "dumbo_rat", label: "Dumbo Rat" },
            { key: "hairless_rat", label: "Hairless Rat" },
            { key: "other", label: "Other" },
        ],
        ferret: [
            { key: "standard_ferret", label: "Standard Ferret" },
            { key: "albino_ferret", label: "Albino Ferret" },
            { key: "sable_ferret", label: "Sable Ferret" },
            { key: "silver_ferret", label: "Silver Ferret" },
            { key: "other", label: "Other" },
        ],
        other: [{ key: "other", label: "Other" }],
    },
    other: {
        wildlife: [{ key: "wildlife", label: "Wildlife" }],
        exotic: [{ key: "exotic", label: "Exotic" }],
        other: [{ key: "other", label: "Other" }],
    },
};
