// Animal Categories Module
export const categories = {
    dog: [
        { key: "sporting", label: "Sporting" },
        { key: "hound", label: "Hound" },
        { key: "working", label: "Working" },
        { key: "terrier", label: "Terrier" },
        { key: "toy", label: "Toy" },
        { key: "non_sporting", label: "Non-Sporting" },
        { key: "herding", label: "Herding" },
        { key: "other", label: "Other" },
    ],
    cat: [
        { key: "short_hair", label: "Short Hair" },
        { key: "medium_hair", label: "Medium Hair" },
        { key: "long_hair", label: "Long Hair" },
        { key: "hairless", label: "Hairless" },
        { key: "other", label: "Other" },
    ],
    horse: [
        { key: "riding", label: "Riding" },
        { key: "working", label: "Working" },
        { key: "pony", label: "Pony" },
        { key: "miniature", label: "Miniature" },
        { key: "other", label: "Other" },
    ],
    livestock: [
        { key: "cattle", label: "Cattle" },
        { key: "sheep", label: "Sheep" },
        { key: "pig", label: "Pig" },
        { key: "goat", label: "Goat" },
        { key: "llama_alpaca", label: "Llama/Alpaca" },
        { key: "poultry", label: "Poultry" },
        { key: "other", label: "Other" },
    ],
    small_pet: [
        { key: "bird", label: "Bird" },
        { key: "hamster", label: "Hamster" },
        { key: "bunny", label: "Bunny" },
        { key: "guinea_pig", label: "Guinea Pig" },
        { key: "mouse", label: "Mouse" },
        { key: "rat", label: "Rat" },
        { key: "ferret", label: "Ferret" },
        { key: "other", label: "Other" },
    ],
    other: [
        { key: "wildlife", label: "Wildlife" },
        { key: "exotic", label: "Exotic" },
        { key: "other", label: "Other" },
    ],
};
