// Animal Categories Module
export const categories = {
    dog: [
        { key: "sporting", label: "Sporting", plural: "Sporting", route: "sporting" },
        { key: "hound", label: "Hound", plural: "Hounds", route: "hounds" },
        { key: "working", label: "Working", plural: "Working", route: "working" },
        { key: "terrier", label: "Terrier", plural: "Terriers", route: "terriers" },
        { key: "toy", label: "Toy", plural: "Toys", route: "toys" },
        { key: "non_sporting", label: "Non-Sporting", plural: "Non-Sporting", route: "non-sporting" },
        { key: "herding", label: "Herding", plural: "Herding", route: "herding" },
        { key: "other", label: "Other", plural: "Other", route: "other" },
    ],
    cat: [
        { key: "short_hair", label: "Short Hair", plural: "Short Hair", route: "short-hair" },
        { key: "medium_hair", label: "Medium Hair", plural: "Medium Hair", route: "medium-hair" },
        { key: "long_hair", label: "Long Hair", plural: "Long Hair", route: "long-hair" },
        { key: "hairless", label: "Hairless", plural: "Hairless", route: "hairless" },
        { key: "other", label: "Other", plural: "Other", route: "other" },
    ],
    horse: [
        { key: "riding", label: "Riding", plural: "Riding", route: "riding" },
        { key: "working", label: "Working", plural: "Working", route: "working" },
        { key: "pony", label: "Pony", plural: "Ponies", route: "pony" },
        { key: "miniature", label: "Miniature", plural: "Miniature", route: "miniature" },
        { key: "other", label: "Other", plural: "Other", route: "other" },
    ],
    livestock: [
        { key: "cattle", label: "Cattle", plural: "Cattle", route: "cattle" },
        { key: "sheep", label: "Sheep", plural: "Sheep", route: "sheep" },
        { key: "pig", label: "Pig", plural: "Pigs", route: "pigs" },
        { key: "goat", label: "Goat", plural: "Goats", route: "goats" },
        { key: "llama_alpaca", label: "Llama/Alpaca", plural: "Llamas/Alpacas", route: "llamas-alpacas" },
        { key: "poultry", label: "Poultry", plural: "Poultry", route: "poultry" },
        { key: "other", label: "Other", plural: "Other", route: "other" },
    ],
    small_pet: [
        { key: "bird", label: "Bird", plural: "Birds", route: "birds" },
        { key: "hamster", label: "Hamster", plural: "Hamsters", route: "hamsters" },
        { key: "bunny", label: "Bunny", plural: "Bunnies", route: "bunnies" },
        { key: "guinea_pig", label: "Guinea Pig", plural: "Guinea Pigs", route: "guinea-pigs" },
        { key: "mouse", label: "Mouse", plural: "Mice", route: "mice" },
        { key: "rat", label: "Rat", plural: "Rats", route: "rats" },
        { key: "ferret", label: "Ferret", plural: "Ferrets", route: "ferrets" },
        { key: "other", label: "Other", plural: "Other", route: "other" },
    ],
    other: [
        { key: "wildlife", label: "Wildlife", plural: "Wildlife", route: "wildlife" },
        { key: "exotic", label: "Exotic", plural: "Exotic", route: "exotic" },
        { key: "other", label: "Other", plural: "Other", route: "other" },
    ],
};
