export const categories = [
    { key: "sporting", type: "dog", label: "Sporting", plural: "Sporting", route: "sporting" },
    { key: "hound", type: "dog", label: "Hound", plural: "Hounds", route: "hounds" },
    { key: "working_dogs", type: "dog", label: "Working", plural: "Working", route: "working-dogs" },
    { key: "terrier", type: "dog", label: "Terrier", plural: "Terriers", route: "terriers" },
    { key: "toy", type: "dog", label: "Toy", plural: "Toys", route: "toys" },
    { key: "non_sporting", type: "dog", label: "Non-Sporting", plural: "Non-Sporting", route: "non-sporting" },
    { key: "herding", type: "dog", label: "Herding", plural: "Herding", route: "herding" },
    { key: "short_hair", type: "cat", label: "Short Hair", plural: "Short Hair", route: "short-hair" },
    { key: "medium_hair", type: "cat", label: "Medium Hair", plural: "Medium Hair", route: "medium-hair" },
    { key: "long_hair", type: "cat", label: "Long Hair", plural: "Long Hair", route: "long-hair" },
    { key: "hairless", type: "cat", label: "Hairless", plural: "Hairless", route: "hairless" },
    { key: "riding", type: "horse", label: "Riding", plural: "Riding", route: "riding" },
    { key: "working_horses", type: "horse", label: "Working", plural: "Working", route: "working-horses" },
    { key: "pony", type: "horse", label: "Pony", plural: "Ponies", route: "pony" },
    { key: "miniature", type: "horse", label: "Miniature", plural: "Miniature", route: "miniature" },
    { key: "cattle", type: "livestock", label: "Cattle", plural: "Cattle", route: "cattle" },
    { key: "sheep", type: "livestock", label: "Sheep", plural: "Sheep", route: "sheep" },
    { key: "pig", type: "livestock", label: "Pig", plural: "Pigs", route: "pigs" },
    { key: "goat", type: "livestock", label: "Goat", plural: "Goats", route: "goats" },
    {
        key: "llama_alpaca",
        type: "livestock",
        label: "Llama/Alpaca",
        plural: "Llamas/Alpacas",
        route: "llamas-alpacas",
    },
    { key: "poultry", type: "livestock", label: "Poultry", plural: "Poultry", route: "poultry" },
    { key: "bird", type: "small_pet", label: "Bird", plural: "Birds", route: "birds" },
    { key: "hamster", type: "small_pet", label: "Hamster", plural: "Hamsters", route: "hamsters" },
    { key: "bunny", type: "small_pet", label: "Bunny", plural: "Bunnies", route: "bunnies" },
    { key: "guinea_pig", type: "small_pet", label: "Guinea Pig", plural: "Guinea Pigs", route: "guinea-pigs" },
    { key: "mouse", type: "small_pet", label: "Mouse", plural: "Mice", route: "mice" },
    { key: "rat", type: "small_pet", label: "Rat", plural: "Rats", route: "rats" },
    { key: "ferret", type: "small_pet", label: "Ferret", plural: "Ferrets", route: "ferrets" },
    { key: "wildlife", type: "other", label: "Wildlife", plural: "Wildlife", route: "wildlife" },
    { key: "exotic", type: "other", label: "Exotic", plural: "Exotic", route: "exotic" },
];
